/**
 * Pure builder for the admin "plan review" markdown export.
 *
 * Takes a fully-assembled `BlockReviewData` snapshot (gathered by
 * `block-review-loader.ts`) and emits a single self-contained markdown
 * document intended for an objective, critical review of a generated
 * training block.
 *
 * The document leads with a REVIEW RUBRIC (the questions the external
 * reviewer should answer), then the full athlete context, the block
 * configuration, the archetype's own design spec (for grounding), and
 * finally the generated plan week-by-week with every prescribed movement
 * and its parameters. No data is editorialised here — it's a faithful
 * dump so the reviewer can judge quality independently.
 *
 * Pure: no IO, no server imports — unit-testable in isolation.
 */

export type ReviewAthlete = {
  experienceTier: string | null;
  bodyweightKg: number | null;
  trainingDaysPerWeek: number | null;
  allowsTwoADays: boolean | null;
  equipment: string[];
};

export type ReviewLimitation = {
  region: string | null;
  kind: string | null;
  severity: string | null;
  affectedMuscles: string[];
};

export type ReviewTrainingMax = {
  movementName: string;
  oneRmKg: number;
  effectivePercent: number;
  tmKg: number;
  source: string;
};

export type ReviewBlockConfig = {
  archetypeId: string;
  archetypeName: string;
  archetypeOneLiner: string | null;
  weeks: number;
  startedOn: string | null;
  status: string | null;
  goal: string | null;
  secondaryFocus: string | null;
  focusMuscles: string[];
  accessoryVolume: string | null;
  powerEmphasis: boolean | null;
  deloadWeekIndex: number | null;
};

export type ReviewWeekProfile = {
  weekIndex: number;
  intensityLabel: string;
  setIntensities: number[];
  setReps: number | number[];
};

export type ReviewItem = {
  kind: string;
  movementName: string | null;
  /** Pre-formatted sets×reps / duration string, e.g. "3×5" or "20 min". */
  setsReps: string | null;
  /** Pre-formatted intensity string, e.g. "85% TM, RIR 1-2". */
  intensity: string | null;
  tempo: string | null;
  isAmrap: boolean;
  supersetGroup: string | null;
  /** The engine's per-movement selection reason, if any (cleaned). */
  why: string | null;
};

export type ReviewSession = {
  weekIndex: number;
  dayIndex: number;
  slot: string;
  title: string;
  role: string | null;
  modality: string | null;
  effectiveStressLoad: number | null;
  items: ReviewItem[];
};

export type BlockReviewData = {
  generatedAt: string;
  athlete: ReviewAthlete;
  limitations: ReviewLimitation[];
  trainingMaxes: ReviewTrainingMax[];
  block: ReviewBlockConfig;
  /** The archetype's own week-by-week intensity design, for grounding. */
  archetypeWeekProfiles: ReviewWeekProfile[];
  /** Every planned session in the block, ordered week → day → slot. */
  sessions: ReviewSession[];
};

const REVIEW_RUBRIC = `## Reviewer brief

You are a strength-and-conditioning expert performing an **objective, critical review** of a single training block generated by an app's programming engine. The athlete's full context, the block's configuration, the archetype's intended design, and the complete week-by-week prescription follow below. Assess the plan **against the athlete's actual context and the stated archetype intent** — be specific, cite the data, and flag concrete problems rather than generic praise.

Please answer:

1. **Goal fit.** Does the generated plan match the stated archetype intent and the athlete's goal / secondary focus? Where does it drift?
2. **Movement selection.** Are the main lifts, dual-main-lift secondaries, and accessories appropriate for the athlete's experience tier and the listed equipment? Cross-check every accessory against the **Equipment** line above before calling anything unavailable. Flag genuinely odd, redundant, or low-value picks — and, for any movement you'd swap, name the specific replacement and why.
3. **Limitations & safety.** Cross-check every prescribed movement against the active limitations. Flag anything contraindicated or aggravating, and note whether the plan adequately works around each limitation.
4. **Focus muscles.** Do the accessories meaningfully bias the declared focus muscles? Is the dose enough to matter (sets/week), without crowding out the main work?
5. **Volume.** Estimate weekly hard-set volume per muscle group and compare to evidence-based landmarks (MEV/MAV/MRV). Flag under- or over-dosing. Note: each loggable set is rendered as its own line — count line items as sets, not as separate movements.
6. **Intensity & progression.** Is the week-to-week intensity/wave structure coherent? Is the deload placed and sized appropriately? See the design grounding below before judging within-block load progression.
7. **Concurrent interference.** If the block mixes strength and cardio, is the interference managed (sequencing, dose, modality)?
8. **Tendon / durability.** Is there an adequate connective-tissue / durability floor (isometrics, HSR, carries) for this athlete and modality mix?
9. **Redundancy & junk volume.** Any duplicated stimulus or junk volume that could be trimmed without cost? (Distinguish genuine redundancy from the deliberate durability/balance floor described below.)
10. **Overall verdict.** A concise quality grade with the top 3 concrete changes you'd make.

### Design grounding — what is intentional (challenge only with evidence)

The engine is built on two canonical programming systems — Jim Wendler's **5/3/1 Forever** and K. Black's **Tactical Barbell**. The decisions below are deliberate and load-bearing. Treat them as the intended design, not defects. You may still challenge any of them — but only with a specific, cited rationale that it is wrong **for this athlete**, not merely different from another template.

- **Load is held constant within a block; progression happens at the block boundary.** Tactical Barbell is explicit: *"the exact same weight every time, before adding more … a block is 6 weeks."* 5/3/1 increments the training max per cycle (not within it). So **repeated/identical loading weeks within one block are by design** — the app progresses the training max between blocks (informed by the AMRAP top set / estimated-1RM), it does not add linear weight mid-block. Do **not** flag "no within-wave TM bump" or "identical waves" as a defect unless you can cite evidence that within-block linear progression beats block-boundary progression for an athlete of this tier.
- **The AMRAP / PR top set is the within-block progress signal — but only on strength-goal archetypes.** Strength and concurrent-hybrid blocks solicit a true AMRAP top set. Endurance / maintenance / rebuild / hypertrophy archetypes deliberately suppress it (submaximal, "rack before failure" per TB) to protect the shared cardio or recovery budget. A missing AMRAP on a cardio-led block is intentional.
- **The deload is volume-led on strength and intensity-led on cardio.** Strength main sets keep the **heaviest** sets (e.g. 60/70% rather than 50/60% TM) to preserve neuromuscular calibration into the next block — a volume deload, by design. On the cardio side the deload now **reduces intensity**: a VO2 session is downgraded to easy Z2 (or one threshold touch at high frequency) and the alactic finisher is dropped (per 5/3/1's 7th-Week Protocol and TB's deload). Do not flag the retained moderate strength top set, and the high-intensity cardio should already be downgraded — flag it only if it is not.
- **Several accessory slots are guaranteed floors, not gap-fill.** Every block guarantees: a weekly **pull** (scaled to the number of pressing main lifts, with vertical+horizontal plane coverage), a **rotator-cuff** item when the block presses, a **durability/HSR floor** steered to the athlete's running impact and main-lift pattern tendons, and **direct focus-muscle volume** when a focus is declared. These are deliberate balance/tissue coverage, not junk volume — judge them on whether the dose is right, not on whether they could be removed.

### Terminology note
Code/DB use "session"; user-facing copy uses "workout" — both refer to the same thing. AMRAP, TM%, training max and 1RM are general lifting vocabulary used legitimately throughout.

---
`;

function h(level: number, text: string): string {
  return `${"#".repeat(level)} ${text}`;
}

/**
 * Compact equipment summary for the review doc (preset + populated groups +
 * accessories). Pure — lives here, not in the server-only loader, so it stays
 * unit-testable. The nested `accessories` object (bands / rings / pull-up bar /
 * dip belt / vest / sandbag) is surfaced explicitly: it was previously omitted,
 * which made the external reviewer repeatedly flag legitimate band-based prehab
 * (e.g. Monster Walk) as an "equipment mismatch" because it could not see the
 * bands the athlete actually owns.
 */
export function summariseEquipment(equipment: unknown): string[] {
  if (!equipment || typeof equipment !== "object") return [];
  const e = equipment as Record<string, unknown>;
  const out: string[] = [];
  if (typeof e.preset === "string") out.push(`preset: ${e.preset}`);
  for (const key of [
    "bars",
    "plates",
    "dumbbells",
    "kettlebells",
    "machines",
    "cardio",
  ]) {
    const v = e[key];
    if (Array.isArray(v) && v.length > 0) out.push(`${key} (${v.length})`);
    else if (v && typeof v === "object") out.push(key);
  }
  const acc = e.accessories;
  if (acc && typeof acc === "object") {
    const a = acc as Record<string, unknown>;
    if (a.bands === true) {
      out.push(
        typeof a.bandStrength === "string" ? `bands (${a.bandStrength})` : "bands",
      );
    }
    if (a.pullUpBar === true) out.push("pull-up bar");
    if (a.rings === true) out.push("rings");
    if (a.dipBelt === true) {
      out.push(
        typeof a.dipBeltMaxKg === "number"
          ? `dip belt (+${a.dipBeltMaxKg}kg)`
          : "dip belt",
      );
    }
    if (a.ankleWeights === true) out.push("ankle weights");
    if (Array.isArray(a.weightedVest) && a.weightedVest.length > 0) out.push("weighted vest");
    else if (a.weightedVest === true) out.push("weighted vest");
    if (Array.isArray(a.sandbag) && a.sandbag.length > 0) out.push("sandbag");
    else if (a.sandbag === true) out.push("sandbag");
  }
  return out;
}

function fmtKg(n: number | null): string {
  if (n == null || !Number.isFinite(n)) return "—";
  return Number.isInteger(n) ? `${n} kg` : `${Math.round(n * 10) / 10} kg`;
}

function yesNo(v: boolean | null | undefined): string {
  return v == null ? "—" : v ? "Yes" : "No";
}

function joinOrDash(arr: string[]): string {
  return arr.length > 0 ? arr.join(", ") : "—";
}

function repsLabel(reps: number | number[]): string {
  return Array.isArray(reps) ? reps.join("/") : String(reps);
}

function athleteSection(a: ReviewAthlete, lims: ReviewLimitation[]): string {
  const lines: string[] = [
    h(2, "Athlete context"),
    "",
    `- **Experience tier:** ${a.experienceTier ?? "—"}`,
    `- **Bodyweight:** ${fmtKg(a.bodyweightKg)}`,
    `- **Training days/week:** ${a.trainingDaysPerWeek ?? "—"}`,
    `- **Open to two-a-days:** ${yesNo(a.allowsTwoADays)}`,
    `- **Equipment:** ${joinOrDash(a.equipment)}`,
    "",
    h(3, "Active limitations"),
    "",
  ];
  if (lims.length === 0) {
    lines.push("_None recorded._", "");
  } else {
    for (const l of lims) {
      const parts = [l.region ?? "unspecified region", l.kind ?? "unspecified"]
        .filter(Boolean)
        .join(" · ");
      const sev = l.severity ? ` (${l.severity})` : "";
      const muscles =
        l.affectedMuscles.length > 0
          ? ` — affected: ${l.affectedMuscles.join(", ")}`
          : "";
      lines.push(`- **${parts}**${sev}${muscles}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function trainingMaxSection(tms: ReviewTrainingMax[]): string {
  const lines: string[] = [h(2, "Training maxes"), ""];
  if (tms.length === 0) {
    lines.push("_No training maxes set._", "");
    return lines.join("\n");
  }
  lines.push(
    "| Lift | 1RM | TM% | Working TM | Source |",
    "| --- | --- | --- | --- | --- |",
  );
  for (const t of tms) {
    lines.push(
      `| ${t.movementName} | ${fmtKg(t.oneRmKg)} | ${t.effectivePercent}% | ${fmtKg(
        t.tmKg,
      )} | ${t.source} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function blockSection(
  b: ReviewBlockConfig,
  profiles: ReviewWeekProfile[],
): string {
  const lines: string[] = [
    h(2, "Block configuration"),
    "",
    `- **Archetype:** ${b.archetypeName} (\`${b.archetypeId}\`)`,
    ...(b.archetypeOneLiner ? [`  - _${b.archetypeOneLiner}_`] : []),
    `- **Length:** ${b.weeks} weeks${
      b.startedOn ? ` · started ${b.startedOn}` : ""
    }${b.status ? ` · status ${b.status}` : ""}`,
    `- **Deload week:** ${
      b.deloadWeekIndex != null ? `week ${b.deloadWeekIndex + 1}` : "—"
    }`,
    `- **Goal:** ${b.goal ?? "—"}`,
    `- **Secondary focus:** ${b.secondaryFocus ?? "—"}`,
    `- **Focus muscles:** ${joinOrDash(b.focusMuscles)}`,
    `- **Accessory volume:** ${b.accessoryVolume ?? "—"}`,
    `- **Power emphasis:** ${yesNo(b.powerEmphasis)}`,
    "",
  ];

  if (profiles.length > 0) {
    lines.push(
      h(3, "Archetype week design (intended)"),
      "",
      "_The archetype's own per-week intensity plan — compare the generated prescription against this._",
      "",
      "| Week | Phase | Set intensities | Reps |",
      "| --- | --- | --- | --- |",
    );
    for (const p of profiles) {
      const intensities =
        p.setIntensities.length > 0
          ? p.setIntensities.map((i) => `${Math.round(i * 100)}%`).join(" / ")
          : "—";
      lines.push(
        `| ${p.weekIndex + 1} | ${p.intensityLabel} | ${intensities} | ${repsLabel(
          p.setReps,
        )} |`,
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

function formatItem(it: ReviewItem): string {
  const bits: string[] = [];
  bits.push(it.movementName ?? "(unnamed)");
  const params: string[] = [];
  if (it.setsReps) params.push(it.setsReps);
  if (it.intensity) params.push(it.intensity);
  if (it.tempo) params.push(it.tempo);
  if (it.isAmrap) params.push("AMRAP top set");
  if (it.supersetGroup) params.push(`superset ${it.supersetGroup}`);
  const paramStr = params.length > 0 ? ` — ${params.join(", ")}` : "";
  const why = it.why ? `  \n    ↳ _why: ${it.why}_` : "";
  return `  - **[${it.kind}]** ${bits.join("")}${paramStr}${why}`;
}

function planSection(sessions: ReviewSession[]): string {
  const lines: string[] = [h(2, "Generated plan"), ""];
  if (sessions.length === 0) {
    lines.push("_No planned sessions found for this block._", "");
    return lines.join("\n");
  }

  // Group by week.
  const byWeek = new Map<number, ReviewSession[]>();
  for (const s of sessions) {
    const arr = byWeek.get(s.weekIndex) ?? [];
    arr.push(s);
    byWeek.set(s.weekIndex, arr);
  }
  const weeks = Array.from(byWeek.keys()).sort((a, b) => a - b);

  for (const w of weeks) {
    lines.push(h(3, `Week ${w + 1}`), "");
    const daySessions = (byWeek.get(w) ?? []).sort(
      (a, b) => a.dayIndex - b.dayIndex || a.slot.localeCompare(b.slot),
    );
    for (const s of daySessions) {
      const slotTag = s.slot && s.slot !== "single" ? ` (${s.slot.toUpperCase()})` : "";
      const meta: string[] = [];
      if (s.modality) meta.push(s.modality);
      if (s.role) meta.push(`role: ${s.role}`);
      if (s.effectiveStressLoad != null) {
        meta.push(`load: ${Math.round(s.effectiveStressLoad * 10) / 10}`);
      }
      const metaStr = meta.length > 0 ? ` — _${meta.join(" · ")}_` : "";
      lines.push(`- **Day ${s.dayIndex + 1}${slotTag}: ${s.title}**${metaStr}`);
      if (s.items.length === 0) {
        lines.push("  - _(no prescribed items)_");
      } else {
        for (const it of s.items) lines.push(formatItem(it));
      }
    }
    lines.push("");
  }
  return lines.join("\n");
}

export function buildBlockReviewMarkdown(data: BlockReviewData): string {
  const header = [
    h(1, `Training block review — ${data.block.archetypeName}`),
    "",
    `_Generated ${data.generatedAt} for objective review. All data is the athlete's own; nothing has been editorialised._`,
    "",
  ].join("\n");

  return [
    header,
    REVIEW_RUBRIC,
    athleteSection(data.athlete, data.limitations),
    trainingMaxSection(data.trainingMaxes),
    blockSection(data.block, data.archetypeWeekProfiles),
    planSection(data.sessions),
  ].join("\n");
}
