import type { TbNamedSession } from "./types";

const SRC = "Tactical Barbell II: Conditioning";

/** Endurance sessions (Zone-2 aerobic + strength-endurance circuits). */
export const ENDURANCE_SESSIONS: TbNamedSession[] = [
  {
    id: "lss",
    name: "Long Steady State",
    aka: "LSS",
    category: "endurance",
    zone: "aerobic",
    equipment: ["run", "bike", "row"],
    trackable: true,
    scoring: "duration",
    steps: ["Run, cycle, swim or row 45–120 min+ at low intensity (Zone 2)."],
    instructions: "Work long, not hard. It takes a minimum of 30 minutes to induce the target adaptations; 45–60 min+ is best.",
    source: SRC,
  },
  {
    id: "ruck-up",
    name: "Ruck Up",
    category: "endurance",
    zone: "aerobic",
    equipment: ["ruck"],
    loaded: true,
    trackable: true,
    scoring: "duration",
    steps: ["Ruck march with a 22 kg load for 90 min."],
    source: SRC,
  },
  {
    id: "triples",
    name: "Triples",
    category: "endurance",
    zone: "mixed",
    equipment: ["jump-rope", "run", "row"],
    scoring: "rounds",
    rounds: "2",
    steps: ["Jump rope 10 min", "Run 10 min", "Row 10 min"],
    instructions: "2 circuits, no rest.",
    source: SRC,
  },
  {
    id: "fun-run-standard-issue",
    name: "Fun-Run — Standard Issue",
    category: "endurance",
    zone: "mixed",
    equipment: ["run", "bodyweight"],
    scoring: "distance",
    steps: ["10 km LSS run", "A — Burpees × 10", "B — Squats × 20 / Push-ups × 20"],
    instructions: "Run 10 km; every 6 min alternate between A and B until the 10 km is completed.",
    source: SRC,
  },
  {
    id: "fun-run-cannonball",
    name: "Fun-Run — Cannonball Run",
    category: "endurance",
    zone: "mixed",
    equipment: ["run", "kettlebell", "bodyweight"],
    loaded: true,
    scoring: "distance",
    steps: ["5 km LSS run (KB in backpack)", "A — KB Swings × 10 (12–24 kg)", "B — Goblet Squats × 10", "C — Push-ups × 10 (KB in backpack)"],
    instructions: "Run 5 km; every 7 min alternate between A, B and C until the 5 km is completed.",
    source: SRC,
  },
  {
    id: "fun-run-stupid-dark-30",
    name: "Fun-Run — 03 at Stupid Dark 30",
    category: "endurance",
    zone: "mixed",
    equipment: ["run", "bodyweight"],
    scoring: "distance",
    steps: ["10 km run for time (uncomfortable pace)", "A — Push-ups × 25 + Squats × 25", "B — Mountain Climbers × 50 (25/leg)", "C — Burpees × 10 + Sit-ups × 25"],
    instructions: "Run 10 km for time; every 7 min alternate between A, B and C. The timer stops during calisthenics and restarts when you start running again.",
    source: SRC,
  },
  {
    id: "warrior-run",
    name: "Warrior Run",
    category: "endurance",
    zone: "aerobic",
    equipment: ["run"],
    trackable: true,
    scoring: "duration",
    steps: ["Run as far as you can in 45 min."],
    instructions: "Good to include every couple of months to chart progress. Use sparingly.",
    source: SRC,
  },
  {
    id: "se-circuit",
    name: "Strength-Endurance Circuit",
    aka: "SE",
    category: "endurance",
    zone: "strength-endurance",
    equipment: ["bodyweight", "barbell", "kettlebell", "dumbbell", "weight-vest"],
    scoring: "rounds",
    rounds: "3",
    steps: [
      "Choose a cluster of 5–8 exercises covering all major body parts.",
      "Perform each exercise for high reps, resting 30–120 s between exercises.",
      "Rest 2 min at the end of the circuit, then repeat.",
    ],
    instructions:
      "Light resistance, high repetition, short rest (the lower the better, all the way to no rest). For DB/BB use ~15–30% of 1RM; bodyweight + weighted vest also works. Example SE 3×30: Push-ups, Squats, Barbell Rows, Back hyperextensions, Dips, Hamstring curls × 30 each, rest 2 min, repeat ×3.",
    source: SRC,
  },
];
