import type { TbNamedSession } from "./types";

const SRC = "Tactical Barbell II: Conditioning";

/** Core and Grip finishers — bolt-ons after a session. */
export const FINISHER_SESSIONS: TbNamedSession[] = [
  {
    id: "plank-and-shank",
    name: "Plank & Shank",
    category: "core-grip",
    zone: "strength-endurance",
    equipment: ["bodyweight"],
    scoring: "rounds",
    rounds: "1-3",
    steps: ["Plank 1–5 min", "Shank 1–5 min", "Rest 1–2 min", "Repeat ×1–3"],
    instructions: "Shank = static back extension / hyperextension, best off a back-extension bench.",
    source: SRC,
  },
  {
    id: "full-core",
    name: "Full Core",
    category: "core-grip",
    zone: "strength-endurance",
    equipment: ["barbell", "bodyweight"],
    scoring: "rounds",
    steps: ["A) 100 Romanian Deadlifts (20–30% 1RM), rest 3–5 min, 100 Hanging Knees-to-Elbow or Leg Raises", "B) 3 × Plank & Shank (60 s plank / 45 s shank)"],
    instructions: "Do sets of 3, 5, 10, 20 or more for the deadlifts and leg raises. Rest as necessary.",
    source: SRC,
  },
  {
    id: "quarterdeck-core",
    name: "Quarterdeck Core",
    category: "core-grip",
    zone: "strength-endurance",
    equipment: ["bodyweight", "ab-wheel"],
    scoring: "rounds",
    rounds: "5-10",
    steps: ["10 Plank Push-ups", "10 Back Extensions", "10 V-Ups", "5–10 Ab Wheel Rollouts", "Repeat ×5–10 (rest as necessary)"],
    source: SRC,
  },
  {
    id: "progressive-grip-circuit",
    name: "Progressive Grip Circuit",
    category: "core-grip",
    zone: "strength-endurance",
    equipment: ["dumbbell", "farmers"],
    loaded: true,
    scoring: "rounds",
    rounds: "1-3",
    steps: ["100 m Farmer's Walk", "10 DB Overhead Presses", "100 m Farmer's Walk", "10 DB Forearm Reverse Curls", "100 m Farmer's Walk", "10 DB Shrugs", "100 m Farmer's Walk", "10 DB Hammer Curls", "Rest 2–3 min", "Repeat ×1–3"],
    instructions: "Use the same pair of DBs for the whole session (start 10–25 kg). Don't put them down. When you can do the full workout without setting them down, add 2.5–5 kg. Indoors, substitute the walk with a 90 s static hold by your sides.",
    source: SRC,
  },
];

/**
 * Challenge sessions — "test your limits, once every couple months, fully
 * rested. Not a routine part of training."
 */
export const CHALLENGE_SESSIONS: TbNamedSession[] = [
  {
    id: "duku-duku",
    name: "Duku-Duku",
    aka: "Pretorian Hills",
    category: "challenge",
    zone: "mixed",
    equipment: ["hill", "kettlebell"],
    loaded: true,
    scoring: "rounds",
    rounds: "5",
    steps: ["5 KB Goblet Squats (24 kg)", "Hill run", "10 KB Swings", "Walk down", "Repeat ×5"],
    instructions: "The kettlebell can't touch the ground for the duration of the workout.",
    source: SRC,
  },
  {
    id: "burpees-for-the-mentally-disturbed",
    name: "Burpees for the Mentally Disturbed",
    category: "challenge",
    zone: "anaerobic",
    equipment: ["bodyweight"],
    scoring: "amrap",
    amrapMin: 10,
    steps: ["AMRAP 10 min Burpees — record the count", "Rest 3 min", "AMRAP 10 min Burpees"],
    instructions: "Try to beat the first-set count on the second set. Don't pace or sandbag the first set.",
    source: SRC,
  },
  {
    id: "tiska-deka-phobia",
    name: "Tiska-Deka-Phobia",
    category: "challenge",
    zone: "mixed",
    equipment: ["ruck", "run"],
    loaded: true,
    trackable: true,
    scoring: "for-time",
    steps: ["21 km Ruck March (25 kg load)", "21 km Run"],
    instructions: "For time. Drop the ruck for the run portion.",
    source: SRC,
  },
  {
    id: "beasting",
    name: "Beasting",
    category: "challenge",
    zone: "mixed",
    equipment: ["ruck", "kettlebell"],
    loaded: true,
    scoring: "for-time",
    steps: ["5 km Ruck Hike/March (48 kg KB load)", "Every 10 min: 100 KB Swings OR 100 Weighted Squats (alternate)"],
    instructions: "For time. The timer stops during swings/squats and restarts when you ruck up and start walking.",
    source: SRC,
  },
  {
    id: "snake-eaters-delight",
    name: "Snake-Eater's Delight",
    category: "challenge",
    zone: "mixed",
    equipment: ["ruck", "run"],
    loaded: true,
    scoring: "for-time",
    steps: ["Day 1: 10 km Ruck March (25 kg) + 10 km Run, for time. Evening: sleep deprivation.", "Day 2: 10 km Ruck March (25 kg) + 10 km Run, for time."],
    instructions: "Stay awake the entire night — no sleep, no naps. Begin Day 2 any time after 05:00. Try to match or beat Day 1 timings.",
    source: SRC,
  },
];
