import type { TbNamedSession } from "./types";

const SRC = "Tactical Barbell II: Conditioning";

/**
 * General Conditioning (GC) circuits — master list #25–36 (labelled GC #1–12).
 * "Do not use GC as the sole source of your HIC work — mix them with the
 * aerobic/anaerobic HICs #1–20."
 */
export const GC_SESSIONS: TbNamedSession[] = [
  {
    id: "gc-1-beat-your-face",
    name: "GC #1 — Beat Your Face",
    category: "gc",
    zone: "mixed",
    hicNumber: 25,
    equipment: ["bodyweight"],
    scoring: "rounds",
    rounds: "1-3",
    steps: ["Burpees × 3 min", "Rest 3 min", "Burpees × 2 min", "Rest 2 min", "Burpees × 1 min", "Rest 1 min", "Repeat ×1–3"],
    source: SRC,
  },
  {
    id: "gc-2",
    name: "GC #2",
    category: "gc",
    zone: "mixed",
    hicNumber: 26,
    equipment: ["pull-up-bar", "bodyweight"],
    scoring: "for-time",
    steps: ["10 Pull-ups", "10 Burpees", "10 Squat Jumps", "10 Plyometric Push-ups", "then 9/8/7/6/5/4/3/2/1"],
    instructions: "Descending ladder from 10 down to 1 reps of each, for time.",
    source: SRC,
  },
  {
    id: "gc-3-brig-rat",
    name: "GC #3 — Brig Rat",
    category: "gc",
    zone: "mixed",
    hicNumber: 27,
    equipment: ["bodyweight"],
    scoring: "rounds",
    rounds: "3-5",
    steps: ["Burpees × 30 s", "Dips × 30 s", "Squats × 30 s", "Burpees × 30 s", "Back extensions / plank × 30 s", "Rest 1 min", "Repeat ×3–5"],
    source: SRC,
  },
  {
    id: "gc-4",
    name: "GC #4",
    category: "gc",
    zone: "mixed",
    hicNumber: 28,
    equipment: ["pull-up-bar", "bodyweight", "run", "kettlebell", "dumbbell"],
    scoring: "for-time",
    steps: ["100 Pull-ups", "Run 400 m", "100 Push-ups", "Run 400 m", "100 KB/DB Swings", "Run 400 m"],
    instructions: "For time.",
    source: SRC,
  },
  {
    id: "gc-5",
    name: "GC #5",
    category: "gc",
    zone: "mixed",
    hicNumber: 29,
    equipment: ["bodyweight", "pull-up-bar"],
    scoring: "rounds",
    steps: ["A) Dips × 1 min, rest 90 s, Push-ups × 1 min, rest 90 s — repeat ×3", "B) 5 Pull-ups, 10 Burpees — repeat ×3"],
    instructions: "Complete 'A' entirely, rest 2 min, then complete 'B'.",
    source: SRC,
  },
  {
    id: "gc-6",
    name: "GC #6",
    category: "gc",
    zone: "mixed",
    hicNumber: 30,
    equipment: ["sledgehammer", "kettlebell", "dumbbell", "bodyweight"],
    scoring: "amrap",
    amrapMin: 5,
    rounds: "3",
    steps: ["AMRAP 5 min: 10 Sledgehammer Tire Strikes (or KB/DB Swings), 5 Burpees, 10 Squats", "Rest 60–90 s", "Repeat ×3"],
    source: SRC,
  },
  {
    id: "gc-7",
    name: "GC #7",
    category: "gc",
    zone: "mixed",
    hicNumber: 31,
    equipment: ["bodyweight", "run"],
    scoring: "for-time",
    rounds: "3",
    steps: ["50 Burpees", "50 Squats", "50 Diamond Push-ups", "Run 800 m", "Repeat ×3 for time"],
    source: SRC,
  },
  {
    id: "gc-8",
    name: "GC #8",
    category: "gc",
    zone: "mixed",
    hicNumber: 32,
    equipment: ["kettlebell", "dumbbell", "box", "pull-up-bar", "bodyweight"],
    scoring: "for-time",
    steps: ["A) 10 KB/DB Snatch per arm, 25 Box Jumps, 25 Hanging Knees-to-Elbow, 25 Dips, 5 Burpees — repeat ×4 for time", "B) Handstand static hold × 60 s, rest 2–3 min — repeat ×3"],
    instructions: "Complete 'A', then complete 'B'.",
    source: SRC,
  },
  {
    id: "gc-9",
    name: "GC #9",
    category: "gc",
    zone: "mixed",
    hicNumber: 33,
    equipment: ["pull-up-bar", "bodyweight", "sprint"],
    scoring: "amrap",
    amrapMin: 10,
    steps: ["A) AMRAP 10 min: 3 Pull-ups, 5 Burpees, 10 Squats", "B) Sprint 100 m × 10"],
    instructions: "Complete 'A', then 'B'. Aim for continuous work.",
    source: SRC,
  },
  {
    id: "gc-10",
    name: "GC #10",
    category: "gc",
    zone: "mixed",
    hicNumber: 34,
    equipment: ["run", "bodyweight"],
    scoring: "rounds",
    rounds: "4",
    steps: ["A) Jog 2 min (active recovery), 25 Burpees as fast as possible — repeat ×4", "B) Core or grip finisher of your choice"],
    source: SRC,
  },
  {
    id: "gc-11-outside-the-wire",
    name: "GC #11 — Outside the Wire",
    category: "gc",
    zone: "mixed",
    hicNumber: 35,
    equipment: ["sprint", "bodyweight", "sledgehammer", "pull-up-bar"],
    scoring: "for-time",
    steps: ["A) Sprint 100 m, Bear Crawl 50 m — repeat ×5 for time", "B) 100 Sledgehammer Tire Strikes for time"],
    instructions: "Complete 'A', then 'B'. No rest. Substitute the sledge with 10 Muscle-Ups OR 50 Pull-ups OR 100 Kipping Pull-ups.",
    source: SRC,
  },
  {
    id: "gc-12",
    name: "GC #12",
    category: "gc",
    zone: "mixed",
    hicNumber: 36,
    equipment: ["run", "barbell", "pull-up-bar", "bodyweight"],
    scoring: "for-time",
    rounds: "3",
    steps: ["A) Run 2.5 km for time", "B) 20 Barbell Push-Press (15–30% 1RM), 20 Back Extensions, 20 Pull-ups — repeat ×3 for time"],
    source: SRC,
  },
];

/**
 * HIC Power Development #37–40. "Sprinkle in occasionally — the majority of HIC
 * training should come from #1–36. Plyometric movements should be explosive."
 */
export const POWER_SESSIONS: TbNamedSession[] = [
  {
    id: "bw-plyometric-power",
    name: "BW Plyometric Power",
    category: "power",
    zone: "power",
    hicNumber: 37,
    equipment: ["bodyweight", "pull-up-bar", "sprint"],
    scoring: "rounds",
    rounds: "3",
    steps: ["A) 10 Plyometric Push-ups, rest 90 s, 10 Jump Squats, rest 90 s, 5–10 Plyometric Pull-ups, rest 2 min — repeat ×3", "B) Sprint 50 m × 3"],
    source: SRC,
  },
  {
    id: "power-complex",
    name: "Power Complex",
    category: "power",
    zone: "power",
    hicNumber: 38,
    equipment: ["barbell", "kettlebell", "dumbbell", "bodyweight"],
    scoring: "rounds",
    rounds: "3",
    steps: ["5 Barbell Push-Press (60–70% 1RM)", "Rest 1–2 min", "10 Double KB/DB Squat Jumps (8–24 kg)", "Rest 1–2 min", "5 KB/DB Snatch per arm (8–24 kg)", "Rest 1–2 min", "5 Plyometric Push-ups", "Rest 1–2 min", "Repeat ×3"],
    instructions: "Maximum speed and explosiveness, under control with good form. Barbell: explosive up, slow down. Push-ups: explosive up, drop down.",
    source: SRC,
  },
  {
    id: "kinetic-conditioning",
    name: "Kinetic Conditioning",
    category: "power",
    zone: "power",
    hicNumber: 39,
    equipment: ["sprint", "bodyweight"],
    scoring: "rounds",
    rounds: "3",
    steps: ["Sprint 50 m + 5 Plyometric Push-ups", "Rest 2 min", "Sprint 50 m + 5 Plyometric Squat Jumps", "Rest 2 min", "Repeat ×3"],
    instructions: "Long rest means max effort — take more rest if needed.",
    source: SRC,
  },
  {
    id: "transition-complex",
    name: "Transition Complex",
    category: "power",
    zone: "power",
    hicNumber: 40,
    equipment: ["barbell", "bodyweight", "pull-up-bar", "med-ball"],
    loaded: true,
    scoring: "rounds",
    rounds: "2-3",
    steps: ["3 Front Squat (85% 1RM) + 10 Plyometric Squat Jumps", "Rest 2 min", "3 Standing Overhead Press (85% 1RM) + 10 Plyometric Push-ups", "Rest 2 min", "3 Weighted Pull-ups (5–25 kg) + 10 Medicine Ball Slams", "Repeat ×2–3"],
    source: SRC,
  },
];
