import type { TbNamedSession } from "./types";

const SRC = "Tactical Barbell II: Conditioning";

/**
 * HIC — High Intensity Continuation, the "Aerobic–Anaerobic" master list #1–20.
 *
 * NOTE: the source the library was transcribed from skips HIC #21–24 (the master
 * numbering jumps from #20 here to #25 where General Conditioning begins). Those
 * four sessions are intentionally absent until recovered from the TB2 book; the
 * `hicNumber` field keeps room for them.
 */
export const HIC_SESSIONS: TbNamedSession[] = [
  {
    id: "connaught-10-to-1s",
    name: "Connaught Range 10 to 1s",
    category: "hic",
    zone: "anaerobic",
    hicNumber: 1,
    equipment: ["run", "sprint", "bodyweight"],
    scoring: "for-time",
    steps: ["10 Burpees, 100 m sprint", "9 Burpees, 100 m sprint", "… down to …", "1 Burpee, 100 m sprint"],
    instructions: "Count down from 10 burpees to 1, with a 100 m sprint between each. Go as fast as possible.",
    source: SRC,
  },
  {
    id: "fast-5-tempo",
    name: "Fast 5 Tempo Run",
    category: "hic",
    zone: "threshold",
    hicNumber: 2,
    equipment: ["run"],
    trackable: true,
    scoring: "distance",
    steps: ["5 km run at 80–85% max HR."],
    source: SRC,
  },
  {
    id: "600m-resets",
    name: "600 m Resets",
    category: "hic",
    zone: "anaerobic",
    hicNumber: 3,
    equipment: ["run", "sprint"],
    scoring: "rounds",
    rounds: "6",
    steps: ["Sprint 600 m max effort", "Rest 3–5 min", "Repeat"],
    instructions: "Start from a rested state and go all out — maximum speed after maximum rest.",
    source: SRC,
  },
  {
    id: "indoor-power-intervals",
    name: "Indoor Power Intervals",
    category: "hic",
    zone: "anaerobic",
    hicNumber: 4,
    equipment: ["treadmill", "bike", "row"],
    scoring: "rounds",
    rounds: "5",
    steps: ["2 min treadmill run / air bike / row — max effort", "Rest 3–5 min", "Repeat"],
    source: SRC,
  },
  {
    id: "sledge-drill",
    name: "Sledge Drill",
    category: "hic",
    zone: "mixed",
    hicNumber: 5,
    equipment: ["sledgehammer", "jump-rope"],
    scoring: "rounds",
    rounds: "5",
    steps: ["1 min sledgehammer tire strike", "1 min jump rope", "30 s sledgehammer tire strike", "30 s jump rope", "Rest 2–3 min", "Repeat"],
    source: SRC,
  },
  {
    id: "boo",
    name: "Black On Oxygen",
    aka: "BOO",
    category: "hic",
    zone: "mixed",
    hicNumber: 6,
    equipment: ["kettlebell", "run"],
    scoring: "rounds",
    rounds: "5",
    steps: ["60 s KB Swings (16–32 kg)", "800 m run", "Rest 2–3 min", "Repeat"],
    source: SRC,
  },
  {
    id: "boo-2",
    name: "BOO 2",
    category: "hic",
    zone: "mixed",
    hicNumber: 7,
    equipment: ["bodyweight", "run", "sprint"],
    scoring: "rounds",
    rounds: "3",
    steps: ["10 Burpees", "800 m run", "5 Burpees", "400 m run max effort", "Rest 2–3 min", "Repeat"],
    source: SRC,
  },
  {
    id: "fobbit-intervals",
    name: "Fobbit Intervals",
    category: "hic",
    zone: "mixed",
    hicNumber: 8,
    equipment: ["run", "row", "jump-rope", "kettlebell"],
    scoring: "amrap",
    amrapMin: 20,
    steps: ["2 min run / row / skip", "20 KB Swings", "2 min run / row / skip", "10 KB Snatch per arm", "Repeat for 20 min"],
    instructions: "See the TB blog 'FOBBITS: The Answer to Everything' Parts I & II.",
    source: SRC,
  },
  {
    id: "short-hills",
    name: "Short Hills",
    category: "hic",
    zone: "anaerobic",
    hicNumber: 9,
    equipment: ["hill", "sprint"],
    scoring: "rounds",
    rounds: "10",
    steps: ["Hill sprint (10–15 s up)", "Rest 30–60 s", "Repeat"],
    source: SRC,
  },
  {
    id: "oxygen-debt-101",
    name: "Oxygen Debt 101",
    category: "hic",
    zone: "anaerobic",
    hicNumber: 10,
    equipment: ["run", "sprint"],
    scoring: "rounds",
    rounds: "3-4",
    steps: ["200 m run × 3 (rest 30 s between intervals)", "Rest 3 min", "Repeat ×3–4"],
    source: SRC,
  },
  {
    id: "speed-endurance-ladders",
    name: "Speed-Endurance Ladders",
    category: "hic",
    zone: "anaerobic",
    hicNumber: 11,
    equipment: ["run", "sprint"],
    scoring: "ladder",
    steps: ["Run 400 m, rest 40 s", "Run 300 m, rest 30 s", "Run 200 m, rest 20 s", "Run 100 m, rest 10 s", "…then back up the ladder in reverse"],
    instructions: "Work down the ladder and then back up. Runs are max effort.",
    source: SRC,
  },
  {
    id: "meat-eater",
    name: "Meat Eater",
    category: "hic",
    zone: "mixed",
    hicNumber: 12,
    equipment: ["sprint", "kettlebell"],
    scoring: "rounds",
    rounds: "10",
    steps: ["Sprint 100 m", "20 KB Swings (24–48 kg)", "Walk back to start", "Repeat"],
    source: SRC,
  },
  {
    id: "meat-eater-2",
    name: "Meat Eater 2",
    category: "hic",
    zone: "mixed",
    hicNumber: 13,
    equipment: ["kettlebell", "bodyweight"],
    scoring: "for-time",
    rounds: "10",
    steps: ["10 KB Swings (medium/heavy)", "10 Burpees", "Rest 60 s", "Repeat ×10 for time"],
    source: SRC,
  },
  {
    id: "standard-issue-hills",
    name: "Standard Issue Hills",
    category: "hic",
    zone: "anaerobic",
    hicNumber: 14,
    equipment: ["hill", "sprint"],
    scoring: "rounds",
    rounds: "5-10",
    steps: ["5–10 hill sprints", "1–2 min rest intervals"],
    instructions: "Walk or jog down; the rest interval starts at the bottom. Find a hill that takes 30–45 s to sprint up. If only a 10–15 s hill is available, double the reps.",
    source: SRC,
  },
  {
    id: "apex-hills",
    name: "Apex Hills",
    category: "hic",
    zone: "mixed",
    hicNumber: 15,
    equipment: ["hill", "sprint", "kettlebell"],
    scoring: "rounds",
    rounds: "5-10",
    steps: ["Hill sprint", "10 KB Swings (heavy)", "Walk down", "Rest 1–2 min (starts at bottom)", "Repeat"],
    instructions: "See the TB blog 'Conquering Apex: How to Progress'.",
    source: SRC,
  },
  {
    id: "bloody-lungs",
    name: "Bloody Lungs",
    category: "hic",
    zone: "mixed",
    hicNumber: 16,
    equipment: ["hill", "sprint", "bodyweight"],
    scoring: "rounds",
    rounds: "5",
    steps: ["10 Plank Push-ups", "Hill sprint", "10 Burpees", "Walk down", "Repeat"],
    instructions: "Plank push-up: from plank, push up one elbow at a time, do one full push-up, return to plank. The walk down is your rest.",
    source: SRC,
  },
  {
    id: "bloody-lungs-2",
    name: "Bloody Lungs 2",
    category: "hic",
    zone: "mixed",
    hicNumber: 17,
    equipment: ["hill", "sprint", "bodyweight", "kettlebell", "dumbbell"],
    scoring: "rounds",
    rounds: "5-10",
    steps: ["10 Burpees", "Hill sprint", "5 KB/DB Snatches per arm", "Walk down", "Rest 1–2 min", "Repeat"],
    source: SRC,
  },
  {
    id: "anaerobic-capacity",
    name: "Anaerobic Capacity",
    category: "hic",
    zone: "anaerobic",
    hicNumber: 18,
    equipment: ["run", "sprint", "bodyweight"],
    scoring: "for-time",
    steps: ["Jog 800 m, Sprint 400 m", "Jog 800 m, Sprint 400 m", "Jog 400 m, Sprint 200 m", "Jog 400 m, Sprint 200 m", "50 Plank Push-ups"],
    source: SRC,
  },
  {
    id: "buffalo-laps",
    name: "Buffalo Laps",
    category: "hic",
    zone: "mixed",
    hicNumber: 19,
    equipment: ["bodyweight", "run", "kettlebell"],
    scoring: "for-time",
    rounds: "4",
    steps: ["10 Burpees", "Run 400 m", "10 two-handed KB Swings", "Rest 45–60 s", "Repeat ×4 for time"],
    source: SRC,
  },
  {
    id: "meat-eater-3",
    name: "Meat Eater 3",
    category: "hic",
    zone: "mixed",
    hicNumber: 20,
    equipment: ["kettlebell", "dumbbell", "sprint"],
    scoring: "rounds",
    rounds: "4-6",
    steps: ["Double KB/DB Clean & Press × 10 (16–32 kg)", "Sprint 300 m", "Lunge 100 m back to start", "Repeat"],
    source: SRC,
  },
];
