/**
 * Integration: equipment preset routes to the correct step at the
 * Training Maxes slot.
 *
 * Renders the wizard with two equipment presets:
 *   1. `home_gym` (has loadable main lift) → TM step renders, the
 *      progress pill labels include "Training maxes".
 *   2. `bodyweight_only` (no loadable main lift) → BW assessment step
 *      renders at the same index, progress pills show
 *      "Bodyweight assessment" instead.
 *
 * The wizard is `"use client"` but its initial render is a static
 * tree at step=0 (Welcome), so renderToStaticMarkup produces enough
 * markup to assert the progress-pill aria-labels. We don't try to
 * navigate — the per-step branch is exercised by reading the
 * `aria-label`s generated by `ProgressPills` from `visibleStepLabels`.
 */
import { describe, it, expect, vi } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import { OnboardingWizard } from "../OnboardingWizard";
import {
  BODYWEIGHT_ONLY_PRESET,
  HOME_GYM_PRESET,
} from "@/lib/settings/equipment-presets";

// next/navigation isn't called on the initial Welcome-step render but
// the module is imported transitively — stub it so the suite doesn't
// fail in node.
vi.mock("next/navigation", () => ({
  useRouter: () => ({ push: () => {}, refresh: () => {} }),
}));

const noopProfile = async () => ({ ok: true as const });
const noopEquipment = async () => undefined;
const noopBw = async () => ({ ok: true as const });
const noopConnect = async () => undefined;
const noopImport = async () => ({
  ok: true as const,
  summary: {
    imported: 0,
    skipped: { strength: 0, sport: 0, other: 0, duplicates: 0, unknown: 0 },
    matchedToPlanned: 0,
    errors: [],
  },
});

function render(preset: typeof HOME_GYM_PRESET | typeof BODYWEIGHT_ONLY_PRESET) {
  return renderToStaticMarkup(
    <OnboardingWizard
      initialDisplayName=""
      initialUnits="metric"
      initialBodyweightKg={null}
      initialEquipment={preset}
      hasEquipmentRow={true}
      roleCandidates={[]}
      initialStravaConnected={false}
      stravaIsConfigured={false}
      saveProfileAction={noopProfile}
      saveEquipmentAction={noopEquipment}
      saveTmsAction={noopProfile}
      submitBwAssessmentAction={noopBw}
      connectStravaAction={noopConnect}
      importStravaHistoryAction={noopImport}
      finishAction={noopProfile}
      skipAction={async () => {}}
    />,
  );
}

describe("OnboardingWizard equipment-aware routing", () => {
  it("home_gym preset surfaces a 'Training maxes' progress pill", () => {
    const html = render(HOME_GYM_PRESET);
    expect(html).toMatch(/aria-label="Step 4 of 7: Training maxes"/);
    expect(html).not.toMatch(/Bodyweight assessment/);
  });

  it("bodyweight_only preset renames the slot to 'Bodyweight assessment'", () => {
    const html = render(BODYWEIGHT_ONLY_PRESET);
    expect(html).toMatch(/aria-label="Step 4 of 7: Bodyweight assessment"/);
    expect(html).not.toMatch(/Step 4 of 7: Training maxes/);
  });

  it("includes a Connect Strava pill as the second-to-last step", () => {
    const html = render(HOME_GYM_PRESET);
    expect(html).toMatch(/aria-label="Step 6 of 7: Connect Strava"/);
    expect(html).toMatch(/aria-label="Step 7 of 7: Confirm"/);
  });
});
