// AUTO-GENERATED by scripts/generate-splash.mjs — do not edit by hand.
// Run `node scripts/generate-splash.mjs` to regenerate after changing the
// device matrix or brand lockup.

export type AppleSplashScreen = { url: string; media: string };

export const APPLE_SPLASH_SCREENS: AppleSplashScreen[] = [
  {
    "url": "/splash/apple-splash-640-1136.png",
    "media": "screen and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-750-1334.png",
    "media": "screen and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1242-2208.png",
    "media": "screen and (device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1125-2436.png",
    "media": "screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-828-1792.png",
    "media": "screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1242-2688.png",
    "media": "screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1170-2532.png",
    "media": "screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1284-2778.png",
    "media": "screen and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1179-2556.png",
    "media": "screen and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1290-2796.png",
    "media": "screen and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1206-2622.png",
    "media": "screen and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1320-2868.png",
    "media": "screen and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1536-2048.png",
    "media": "screen and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1620-2160.png",
    "media": "screen and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1640-2360.png",
    "media": "screen and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1668-2224.png",
    "media": "screen and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-1668-2388.png",
    "media": "screen and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "url": "/splash/apple-splash-2048-2732.png",
    "media": "screen and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  }
];
