import { NextResponse } from "next/server";
import { createClient, getAuthUser } from "@/lib/supabase/server";

/**
 * GDPR Article 15 / 20 — right to access + portability.
 *
 *   GET /api/me/export
 *
 * Returns every datum the app holds on the authenticated user as a single
 * JSON document. RLS-scoped via the user-scoped Supabase client (no
 * admin-key bypass), so each query already returns only the caller's own
 * rows.
 *
 * ── Format contract ──────────────────────────────────────────────────
 * `schema` is the stable format identifier; `format_version` is an integer
 * bumped ONLY on a breaking change. Within a `format_version`, changes are
 * **additive** — new top-level sections or new fields may appear, but
 * existing sections/fields are never renamed or removed without a format
 * version bump. Consumers should ignore unknown keys and tolerate new sections.
 * This contract is
 * documented in `docs/export-format.md` and pinned by
 * `apps/web/src/app/api/me/export/__tests__/route.test.ts`.
 *
 * ── What's included ──────────────────────────────────────────────────
 * Every user-authored / user-state table: profile, training maxes (+ their
 * change history), training blocks + planned sessions, logged sessions with
 * their sets, off-plan session movements, cardio logs, wellness, limitations
 * (+ event log), races (priority events), bodyweight progression,
 * prescription modifications, engine override events,
 * region state, and the user's custom movements. Movement-referencing rows
 * are joined to `{slug, display_name}` so the export is portable without the
 * opaque catalog UUIDs.
 *
 * ── What's intentionally excluded (and why) ──────────────────────────
 *   - Strava OAuth tokens (`strava_connections`) never leave their subsystem.
 *   - Derived / recomputable snapshots are omitted to keep the export to
 *     authored data: `tm_suggestions`, `region_state_history`,
 *     `muscle_state_history`, `bw_diagnostics_snapshots`.
 *     These are regenerated by the engine from the included data.
 *   - The global movement catalog (`movements.user_id IS NULL`) is not
 *     personal data; only the user's own custom movements are exported.
 */

const FORMAT_VERSION = 2;

const MOVEMENT_JOIN = "*, movement:movements(slug, display_name)";

function exportProfile(
  row: Record<string, unknown> | null,
): Record<string, unknown> | null {
  if (!row) return null;
  const cleaned = { ...row };
  const trainingNotes = cleaned.ai_notes;
  delete cleaned.ai_notes;
  delete cleaned.byoai_provider;
  delete cleaned.byoai_key_vault_id;
  delete cleaned.byoai_model;
  delete cleaned.byoai_unlocked_at;
  return { ...cleaned, training_notes: trainingNotes ?? null };
}

export async function GET() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await getAuthUser();
  if (!user) {
    return NextResponse.json({ error: "Not signed in." }, { status: 401 });
  }

  const [
    profile,
    trainingMaxes,
    tmHistory,
    trainingBlocks,
    plannedSessions,
    sessions,
    sessionMovements,
    setLogs,
    cardioLogs,
    wellness,
    limitations,
    limitationEvents,
    priorityEvents,
    bwProgress,
    bwProgressionEvents,
    prescriptionModifications,
    engineOverrideEvents,
    regionState,
    customMovements,
  ] = await Promise.all([
    supabase.from("profiles").select("*").eq("id", user.id).maybeSingle(),
    supabase.from("training_maxes").select(MOVEMENT_JOIN).order("created_at", { ascending: true }),
    supabase.from("tm_history").select(MOVEMENT_JOIN).order("changed_at", { ascending: true }),
    supabase.from("training_blocks").select("*").order("created_at", { ascending: true }),
    supabase.from("planned_sessions").select("*").order("created_at", { ascending: true }),
    supabase.from("sessions").select("*").order("performed_at", { ascending: true }),
    supabase.from("session_movements").select(MOVEMENT_JOIN).order("added_at", { ascending: true }),
    supabase.from("set_logs").select(MOVEMENT_JOIN).order("created_at", { ascending: true }),
    supabase.from("cardio_logs").select(MOVEMENT_JOIN).order("created_at", { ascending: true }),
    supabase.from("wellness").select("*").order("date", { ascending: true }),
    supabase.from("limitations").select("*").order("started_at", { ascending: true }),
    supabase.from("limitation_events").select("*").order("occurred_at", { ascending: true }),
    supabase.from("priority_events").select("*").order("created_at", { ascending: true }),
    supabase.from("bw_progress").select("*"),
    supabase.from("bw_progression_events").select("*").order("occurred_at", { ascending: true }),
    supabase.from("prescription_modifications").select("*"),
    supabase.from("engine_override_events").select("*").order("occurred_at", { ascending: true }),
    supabase.from("region_state").select("*"),
    supabase.from("movements").select("*").eq("user_id", user.id),
  ]);

  const exportedAt = new Date().toISOString();
  const payload = {
    schema: "hybrid-training-app/export-v2",
    format_version: FORMAT_VERSION,
    exported_at: exportedAt,
    user: {
      id: user.id,
      email: user.email,
      created_at: user.created_at,
    },
    profile: exportProfile(profile.data),
    training_maxes: trainingMaxes.data ?? [],
    tm_history: tmHistory.data ?? [],
    training_blocks: trainingBlocks.data ?? [],
    planned_sessions: plannedSessions.data ?? [],
    sessions: sessions.data ?? [],
    session_movements: sessionMovements.data ?? [],
    set_logs: setLogs.data ?? [],
    cardio_logs: cardioLogs.data ?? [],
    wellness: wellness.data ?? [],
    limitations: limitations.data ?? [],
    limitation_events: limitationEvents.data ?? [],
    priority_events: priorityEvents.data ?? [],
    bw_progress: bwProgress.data ?? [],
    bw_progression_events: bwProgressionEvents.data ?? [],
    prescription_modifications: prescriptionModifications.data ?? [],
    engine_override_events: engineOverrideEvents.data ?? [],
    region_state: regionState.data ?? [],
    custom_movements: customMovements.data ?? [],
    excluded: {
      secrets: ["strava_connections"],
      derived: [
        "tm_suggestions",
        "region_state_history",
        "muscle_state_history",
        "bw_diagnostics_snapshots",
      ],
      note:
        "Secrets are withheld so at-rest encryption is not defeated. Derived " +
        "tables are recomputable by the engine from the included data. The " +
        "global movement catalog is not personal data.",
    },
    notes:
      "This file is the complete record of every datum the app holds on you, " +
      "excluding the secrets and derived tables listed under `excluded`. " +
      "Movement-referencing rows are joined to {slug, display_name} so the " +
      "export is portable without internal catalog IDs.",
  };

  const filename = `hta-export-${user.id}-${exportedAt.slice(0, 10)}.json`;
  return new NextResponse(JSON.stringify(payload, null, 2), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store, max-age=0",
    },
  });
}
