"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import type { Prescription, PrescriptionItem } from "@hta/db";

/**
 * Wire shape for `planned_sessions` INSERTs via the Supabase REST API.
 *
 * PostgREST takes the literal JS keys you send and looks them up as
 * column names — it does NOT translate from Drizzle's camelCase property
 * names to the underlying snake_case DB columns. The Drizzle-derived
 * `NewPlannedSession` type uses camelCase (blockId, userId, weekIndex,
 * …) which PostgREST rejects with PGRST204 ("Could not find the
 * 'blockId' column of 'planned_sessions' in the schema cache").
 *
 * This type is intentionally typed against the *DB column names* so the
 * TypeScript compiler will reject any future drift back to camelCase.
 */
type PlannedSessionInsertRow = {
  block_id: string;
  user_id: string;
  week_index: number;
  day_index: number;
  slot: "single" | "am" | "pm";
  title: string;
  role: string;
  prescription: Prescription;
  /**
   * Phase 5 — modality classifier output. NULL on rows generated by
   * code paths that opted out of the classifier (none today, but the
   * column is nullable in the DB so legacy callers stay valid).
   */
  session_modality?: SessionModality | null;
  /**
   * Phase 5 — hard-set count × modality multiplier. NULL when the
   * session has no hard sets (rest day, etc.) or when the modality
   * could not be computed.
   */
  effective_stress_load?: number | null;
};
import { createClient, getAuthUser } from "@/lib/supabase/server";
import { todayYmd, ymdToUtc, daysBetweenYmd } from "@/lib/dates";
import { getUserTimezone } from "./queries";
import {
  ARCHETYPES,
  type Archetype,
  type ArchetypeId,
  type DayTemplate,
  type StrengthDay,
  allCandidateLiftSlugs,
  daysForFrequency,
  daySlotKey,
  minDaysForArchetype,
  requiredFixedSlugs,
  resolveCardioSlugForTier,
  STRENGTH_ROLE_LABELS,
} from "./archetypes";
import { allAccessorySlugs } from "./accessories";
import { foldDualMainLifts } from "./main-lift-folding";
import { assemblePrescriptionItems } from "./assemble-prescription";
import {
  applyPlacementsToActiveDays,
  dayIndexOverridesSchema,
  type DayIndexOverrides,
} from "./wizard/placements";
import { sanitiseSlotForMode } from "./slot";
import { swapPlannedSessions } from "./swap";
import { recordOverrideEvent } from "@/lib/engine/overrides";
import {
  type CatalogMovement,
  type WeekContextItem,
} from "./accessory-picker";
import {
  type LimitationsContext,
  readLimitationsContext,
} from "./limitations-context";
import { loadPickerCatalog } from "./picker-catalog";
import type { DeclaredExperience } from "@hta/engine";
import { declaredExperienceToTier, tierInBand } from "./experience-tier";
import {
  resolveWarmupScheme,
} from "./warmups";
import { resolveEquipment } from "@/lib/settings/equipment-presets";
import { hasLoadableMainLift } from "@/lib/settings/equipment-presets";
import type { Equipment } from "@/lib/settings/equipment-schema";
import type { MovementFamily, MovementNode } from "@hta/db";
import {
  buildBwMainItemsForSession,
  type BwFamilyContext,
} from "./bw-main-items";
import {
  classifySessionModality,
  effectiveStressLoad,
  type ClassifierMovement,
  type SessionModality,
} from "./session-modality";
import {
  maybeInjectHingeCompensation,
  HINGE_COMPENSATION_FAMILY,
} from "./hinge-compensation";
import type { BwProgress } from "@hta/db";
import { focusMusclesSchema, type FocusMuscle } from "./focus-muscles";
import { getElbowForearmAtlRatio } from "@/lib/stats/region-spike-queries";
import { getPreviousBlockAccessoryIdsByRole } from "./accessory-history-queries";

/**
 * Movement-row shape used by the main-lift resolver. Only the columns
 * actually read at the call site — the resolver doesn't need the full
 * `DbMovement` projection (no muscles / roles / scores).
 */
type StrengthMovementRow = {
  id: string;
  slug: string;
  display_name: string;
  experience_min: number | null;
  experience_max: number | null;
};

/**
 * PR W2 — pick the first candidate slug whose movement falls within
 * the user's experience band AND has a TM logged. Encodes Surface B
 * (main-lift resolver) so a user with TMs for `[back-squat-high-bar,
 * pause-back-squat]` picks the high-bar at tier 0 and the pause variant
 * only when the band allows it. Tier `null` (no declaration) preserves
 * the legacy "first candidate with a TM" behaviour.
 *
 * Returns `null` if no in-band candidate has a TM — caller handles the
 * out-of-band fallback (use the TM anyway, log a dev warning) so the
 * filter doesn't block training.
 */
function pickStrengthMovementForBand({
  candidateSlugs,
  movementBySlug,
  tmMovementIds,
  tier,
}: {
  candidateSlugs: readonly string[];
  movementBySlug: Map<string, StrengthMovementRow>;
  tmMovementIds: Set<string>;
  tier: number | null;
}): { movementId: string; slug: string; displayName: string } | null {
  for (const slug of candidateSlugs) {
    const mv = movementBySlug.get(slug);
    if (!mv) continue;
    if (!tmMovementIds.has(mv.id)) continue;
    if (!tierInBand(tier, mv.experience_min ?? 0, mv.experience_max ?? 4)) continue;
    return { movementId: mv.id, slug: mv.slug, displayName: mv.display_name };
  }
  return null;
}

/**
 * ADR 0004 — resolve the dual-main-lift secondary movement for a strength
 * day that declares `secondaryCandidateSlugs`. Mirrors the in-band-with-TM
 * → out-of-band-TM fallback used for the primary slot, BUT does **not**
 * fall back to a no-TM catalog reference: if no TM is set anywhere in the
 * secondary candidate list, this returns null and the prescription emits
 * the primary lift only. The secondary slot is opt-in via TM.
 */
function pickSecondaryStrengthMovement({
  candidateSlugs,
  movementBySlug,
  tmMovementIds,
  tier,
}: {
  candidateSlugs: readonly string[];
  movementBySlug: Map<string, StrengthMovementRow>;
  tmMovementIds: Set<string>;
  tier: number | null;
}): { movementId: string; slug: string; displayName: string } | null {
  const inBand = pickStrengthMovementForBand({ candidateSlugs, movementBySlug, tmMovementIds, tier });
  if (inBand) return inBand;
  for (const slug of candidateSlugs) {
    const mv = movementBySlug.get(slug);
    if (mv && tmMovementIds.has(mv.id)) {
      return { movementId: mv.id, slug: mv.slug, displayName: mv.display_name };
    }
  }
  return null;
}

/**
 * Whitelist the 5 declared experience tiers shipped in migration 0052.
 * Anything else (null, legacy values, undeclared) collapses to null so
 * the accessory picker treats the user as "not declared" and keeps the
 * pre-PR-W1 behaviour (no filtering).
 */
const DECLARED_EXPERIENCE_VALUES: ReadonlySet<DeclaredExperience> = new Set([
  "beginner_lt_6m",
  "novice_6m_2y",
  "intermediate_2y_5y",
  "advanced_5y_10y",
  "highly_advanced_10y_plus",
]);

function resolveDeclaredExperience(
  raw: string | null | undefined,
): DeclaredExperience | null {
  if (!raw) return null;
  return DECLARED_EXPERIENCE_VALUES.has(raw as DeclaredExperience)
    ? (raw as DeclaredExperience)
    : null;
}

// ─── Phase 5 — modality classifier + stress-load helpers ─────────────

/**
 * Map a curated CardioDay's `cardioKind` to the classifier's mode tag.
 * The classifier only distinguishes Z2 / HIIT / mixed; finer-grained
 * shapes (alactic vs threshold vs VO2) collapse into HIIT or mixed
 * because they hit the same recovery-cost branch.
 */
function cardioModeFor(
  kind: PrescriptionItem["kind"],
): "z2" | "hiit" | "mixed" {
  if (kind === "cardio_z2") return "z2";
  if (kind === "cardio_alactic" || kind === "cardio_vo2") return "hiit";
  if (kind === "cardio_threshold") return "mixed";
  return "mixed";
}

/**
 * Convert the planned-session prescription `items` array (the same
 * shape that gets serialised onto `planned_sessions.prescription`)
 * into the classifier's input contract.
 *
 * Strength items map by `kind`:
 *   - main → bucket=main
 *   - back_off → bucket=back_off
 *   - accessory / tendon / power_potentiation → bucket=accessory
 *   - warmup → kind=warmup (the classifier ignores these)
 *
 * Cardio items emit a single `cardioBlock` carrying `durationMinutes`.
 * `estimatedHardSets` for cardio is set to 0 — the multiplier covers
 * the recovery cost, the hard-set count is for strength work.
 */
function itemsToClassifierMovements(
  items: ReadonlyArray<PrescriptionItem>,
  archetype: ArchetypeId,
): ClassifierMovement[] {
  const out: ClassifierMovement[] = [];
  for (const it of items) {
    if (it.kind === "warmup") {
      out.push({ kind: "warmup", archetype, estimatedHardSets: 0 });
      continue;
    }
    if (
      it.kind === "cardio_z2" ||
      it.kind === "cardio_alactic" ||
      it.kind === "cardio_vo2" ||
      it.kind === "cardio_threshold" ||
      it.kind === "cardio_external"
    ) {
      out.push({
        kind: "conditioning",
        archetype,
        cardioBlock: {
          // External cardio collapses to z2 for stress-budget purposes:
          // the user is following an outside program so we can't know
          // the actual intensity. Z2 is the safest default — the
          // multiplier under-counts hard runs (acceptable) instead of
          // over-counting easy ones (would suppress strength volume).
          mode: it.kind === "cardio_external" ? "z2" : cardioModeFor(it.kind),
          // Phase 1 — external blocks carry no `durationMin`. 0 lets the
          // calendar / modality classifier still register a cardio day
          // without inflating effective_stress_load against unknown work.
          durationMinutes: it.durationMin ?? 0,
        },
        estimatedHardSets: 0,
      });
      continue;
    }
    const sets = Math.max(0, it.sets ?? 1);
    if (it.kind === "main") {
      out.push({
        kind: "main",
        archetype,
        bucket: "main",
        estimatedHardSets: sets,
        bw: it.bw
          ? {
              prescriptionType: it.bw.prescriptionType,
              family: (it.bw.family as MovementFamily | undefined) ?? "push_h",
              nodeDifficulty: 0,
            }
          : undefined,
      });
      continue;
    }
    if (it.kind === "back_off") {
      out.push({
        kind: "back_off",
        archetype,
        bucket: "back_off",
        estimatedHardSets: sets,
      });
      continue;
    }
    // accessory / tendon / power_potentiation
    out.push({
      kind: "accessory",
      archetype,
      bucket: "accessory",
      estimatedHardSets: sets,
    });
  }
  return out;
}

/**
 * Stamp the modality + effective-stress-load on a planned session.
 * Centralised so createBlock and createCustomBlock produce the same
 * shape — they're the only two callers that build planner rows.
 */
function classifyPlannedSession(
  items: ReadonlyArray<PrescriptionItem>,
  archetype: ArchetypeId,
): { modality: SessionModality; load: number } {
  const movs = itemsToClassifierMovements(items, archetype);
  const modality = classifySessionModality({ movements: movs });
  const hardSets = movs.reduce(
    (acc, m) => acc + (m.kind === "warmup" ? 0 : Math.max(0, m.estimatedHardSets)),
    0,
  );
  const load = effectiveStressLoad({ modality, hardSets });
  return { modality, load };
}

/**
 * Build the prescription-item shape for an injected hinge-compensation
 * movement. The injected item is bucketed as `accessory` so existing
 * focus-view / logging paths render it without special-casing; the
 * `meta.hinge_compensation` flag distinguishes it from a normal
 * accessory pick for downstream consumers (settings page, audit).
 */
function buildHingeCompensationItem(args: {
  movementId: string;
  nodeKey: string;
  prescription: {
    nodeKey: string;
    prescriptionType: "isometric_hold" | "tempo_reps" | "reps";
    sets: number;
    reps?: number;
    holdSeconds?: number;
    tempoEccentricSec: number;
    targetRir: number;
    intensityCue: string;
  };
  displayName: string;
}): PrescriptionItem {
  const p = args.prescription;
  const item: PrescriptionItem = {
    movementId: args.movementId,
    movementSlug: p.nodeKey,
    movementName: args.displayName,
    kind: "accessory",
    sets: p.sets,
    targetRir: { min: p.targetRir, max: p.targetRir },
    tempoEccentricSec: p.tempoEccentricSec,
    intensityCue: p.intensityCue,
    intensityLabel: "hinge compensation",
    notes:
      "Posterior-chain compensation — your session didn't include a hinge pattern.",
    bw: {
      prescriptionType: p.prescriptionType,
      sets: p.sets,
      reps: p.reps,
      holdSeconds: p.holdSeconds,
      tempoEccentricSec: p.tempoEccentricSec,
      targetRir: p.targetRir,
      restSeconds: 90,
      intensityCue: p.intensityCue,
      nodeKey: p.nodeKey,
      nodeDisplayName: args.displayName,
      family: HINGE_COMPENSATION_FAMILY,
    },
    meta: { hinge_compensation: true, hinge_compensation_node: p.nodeKey },
  };
  if (p.prescriptionType === "isometric_hold" && p.holdSeconds != null) {
    item.holdSec = { min: p.holdSeconds, max: p.holdSeconds };
  } else if (p.reps != null) {
    item.reps = p.reps;
  }
  return item;
}

/**
 * Phase 1 "external cardio" — placeholder prescription for a reserved
 * cardio day on a block whose `cardio_source = 'external'`. The pure
 * helper lives in `./external-cardio.ts` so it can be imported from
 * test files (this module is a "use server" boundary — every export
 * must be async).
 */
import { buildExternalCardioItems } from "./external-cardio";


const createBlockSchema = z.object({
  archetype: z.enum([
    "strength_anchor",
    "endurance_anchor",
    "rebuild",
    "hypertrophy_anchor",
    "concurrent_hybrid",
    "maintenance",
  ] satisfies [ArchetypeId, ...ArchetypeId[]]),
  startedOn: z.string().date(),
  daysPerWeek: z.coerce.number().int().min(1).max(7),
  /**
   * Optional JSON-stringified ``DayIndexOverrides`` from the block wizard's
   * "Lay out your week" step. Persisted on the block row so re-runs honour
   * the user's calendar layout. Shape: ``{ days, twoADay, placements? }``
   * — see ``wizard/placements.ts`` for the canonical schema. The
   * `placements` field is optional during the rollout transition; absent
   * payloads (legacy / mid-flight submissions) fall back to canonical
   * day-template ordering.
   */
  dayIndexOverrides: z.string().optional(),
  /**
   * Wizard "Add power emphasis" toggle (step 2). Optional + coerced from
   * FormData ("true" / "false" / "on" / undefined). When omitted or
   * falsy the block is created with power_emphasis = false.
   */
  powerEmphasis: z
    .union([z.literal("true"), z.literal("false"), z.literal("on"), z.boolean()])
    .optional()
    .transform((v) => v === true || v === "true" || v === "on"),
  /**
   * Phase 1 "external cardio". 'external' tells the materialiser to
   * emit a single placeholder `cardio_external` item per cardio day
   * instead of the archetype's prescribed run. Default 'internal'
   * keeps every legacy + new internal block on the existing path.
   */
  cardioSource: z
    .enum(["internal", "external"])
    .optional()
    .transform((v) => v ?? "internal"),
  /**
   * Free-text label for the external program (e.g. "Runna"). Trimmed
   * and capped at 80 chars; empty strings normalise to null at write
   * time so the DB column stays distinguishable.
   */
  cardioSourceName: z
    .string()
    .trim()
    .max(80)
    .optional()
    .transform((v) => (v && v.length > 0 ? v : null)),
  /**
   * Migration 0079 — per-block focus muscle groups (0–2). Submitted as
   * repeated `focusMuscles` fields (FormData.getAll). Server-side
   * validation mirrors the DB CHECK constraints; the DB is the final
   * guard. See `lib/planner/focus-muscles.ts`.
   */
  focusMuscles: focusMusclesSchema,
});

export type CreateBlockResult =
  | { ok: true }
  | { ok: false; error: string };

/**
 * Create a new block from the wizard input. Returns a result object so the
 * client wizard can surface the failure reason inline instead of crashing
 * the whole page.
 */
export async function createBlock(formData: FormData): Promise<CreateBlockResult> {
  const parsed = createBlockSchema.safeParse({
    archetype: formData.get("archetype"),
    startedOn: formData.get("startedOn"),
    daysPerWeek: formData.get("daysPerWeek"),
    dayIndexOverrides: formData.get("dayIndexOverrides") ?? undefined,
    powerEmphasis: formData.get("powerEmphasis") ?? undefined,
    cardioSource: formData.get("cardioSource") ?? undefined,
    cardioSourceName: formData.get("cardioSourceName") ?? undefined,
    // Focus muscles arrive as repeated `focusMuscles` form fields.
    // Empty getAll() → [] → focusMusclesSchema's `.default([])` path.
    focusMuscles: formData
      .getAll("focusMuscles")
      .map((v) => (typeof v === "string" ? v : ""))
      .filter((v) => v.length > 0),
  });
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "Invalid input" };
  }

  // Parse + validate the dayIndexOverrides JSON payload (wizard step 5).
  // Accepts both the legacy `{ days, twoADay }` shape and the post-fix
  // `{ days, twoADay, placements }` shape — Zod's optional `placements`
  // makes the transition safe for any submission that races the deploy.
  let dayIndexOverrides: DayIndexOverrides | null = null;
  if (parsed.data.dayIndexOverrides) {
    try {
      const raw: unknown = JSON.parse(parsed.data.dayIndexOverrides);
      const result = dayIndexOverridesSchema.safeParse(raw);
      if (result.success) {
        dayIndexOverrides = result.data;
      }
    } catch {
      // Bad JSON — silently drop; the block can still be created without overrides.
    }
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await getAuthUser();
  if (!user) redirect("/login");

  const archetype = ARCHETYPES[parsed.data.archetype];
  if (!archetype) return { ok: false, error: "Unknown archetype" };

  // Look up the user's two-a-day preference + warmup-ladder config + equipment so we pick the right day pool, prepend warmups, and only prescribe movements they can actually do.
  const { data: profile } = await supabase
    .from("profiles")
    .select("allows_two_a_days, warmup_scheme, equipment, barbell_kg, trap_bar_kg, plate_inventory_kg, bw_assessment_completed_at, bodyweight_kg, training_experience")
    .eq("id", user.id)
    .maybeSingle();
  const allowsTwoADays = Boolean(profile?.allows_two_a_days ?? false);
  const warmupScheme = resolveWarmupScheme(profile?.warmup_scheme);
  const equipment = resolveEquipment(profile);
  const experience = resolveDeclaredExperience(profile?.training_experience);

  const minDays = minDaysForArchetype(
    archetype,
    allowsTwoADays,
    equipment.preset === "bodyweight_only",
  );
  if (parsed.data.daysPerWeek < minDays) {
    return {
      ok: false,
      error: `${archetype.name} needs at least ${minDays} training days/week.`,
    };
  }
  const canonicalActiveDays = foldDualMainLifts(
    archetype,
    daysForFrequency(archetype, parsed.data.daysPerWeek, allowsTwoADays),
  );
  // Honour the user's Step-5 arrangement (Mon/Tue/Thu/Sat etc.) when the
  // wizard supplied placements. Without this remap the canonical archetype
  // template order leaks through and overrides whatever the user picked.
  // See `wizard/placements.ts` for the matching strategy + fallbacks.
  const activeDays = applyPlacementsToActiveDays(
    canonicalActiveDays,
    dayIndexOverrides?.placements ?? null,
  );

  const candidateSlugs = allCandidateLiftSlugs(archetype);
  const fixedSlugs = requiredFixedSlugs(archetype);
  const accessorySlugs = allAccessorySlugs();
  const allSlugs = Array.from(new Set([...candidateSlugs, ...fixedSlugs, ...accessorySlugs]));

  const { data: movements, error: mvErr } = await supabase
    .from("movements")
    .select("id, slug, display_name, experience_min, experience_max")
    .in("slug", allSlugs)
    .is("user_id", null);
  if (mvErr) return { ok: false, error: `Movement lookup failed: ${mvErr.message}` };

  const movementBySlug = new Map((movements ?? []).map((m) => [m.slug, m]));

  // Picker catalog — full global catalog with role tags. Loaded only when
  // the archetype has an accessoryProfile so legacy archetypes pay nothing.
  let pickerCatalog: CatalogMovement[] = [];
  if (archetype.accessoryProfile) {
    pickerCatalog = await loadPickerCatalog(supabase);
    if (pickerCatalog.length === 0) {
      return { ok: false, error: "Catalog load failed" };
    }
  }

  const missingFixed = fixedSlugs.filter((s) => !movementBySlug.has(s));
  if (missingFixed.length > 0) {
    return {
      ok: false,
      error: `Catalog is missing required movements: ${missingFixed.join(", ")}. Re-seed movements.`,
    };
  }

  const candidateMovementIds = candidateSlugs
    .map((s) => movementBySlug.get(s)?.id)
    .filter((id): id is string => !!id);

  const { data: tms, error: tmErr } = await supabase
    .from("training_maxes")
    .select("movement_id, updated_at")
    .in("movement_id", candidateMovementIds);

  if (tmErr) return { ok: false, error: `TM lookup failed: ${tmErr.message}` };

  const tmByMovementId = new Map((tms ?? []).map((r) => [r.movement_id, r.updated_at]));

  /**
   * Bodyweight-only / no-TM path. When the user has no training maxes
   * at all (e.g. they picked the bodyweight-only equipment preset and
   * skipped the TM step), the planner can't produce %TM-based main
   * lift items. Build the block anyway with accessories + tendon work
   * only — the picker keys off equipment, so a bodyweight setup yields
   * push-up / pull-up / single-leg / plank variants prescribed via
   * RPE / RIR rather than %TM.
   */
  const hasAnyTm = tmByMovementId.size > 0;

  // ─── Bodyweight Phase 3 — main-lift prescription ─────────────────
  // When the user has no loadable kit AND has populated bw_progress
  // (via the Phase 2 assessment wizard), the planner emits BW main +
  // back-off items per session from the per-family DAG node. Detection
  // matches the plan: `!hasLoadableMainLift(equipment)` AND at least
  // one bw_progress row.
  const bwActive = !hasLoadableMainLift(equipment);
  const bwByFamily = new Map<MovementFamily, BwFamilyContext>();
  if (bwActive) {
    const { data: bwRows } = await supabase
      .from("bw_progress")
      .select("family, current_node_id, clean_rep_history")
      .eq("user_id", user.id);
    const nodeIds = (bwRows ?? [])
      .map((r) => r.current_node_id as string | null)
      .filter((id): id is string => !!id);
    if (nodeIds.length > 0) {
      const { data: nodes } = await supabase
        .from("movement_nodes")
        .select(
          "id, family, node_key, display_name, prerequisites, external_load_capable, isometric_capable, unilateral, default_tempo_seconds, tut_per_rep_seconds, difficulty_anchor, created_at",
        )
        .in("id", nodeIds);
      const nodeById = new Map<string, MovementNode>();
      for (const n of nodes ?? []) {
        // PostgREST returns snake_case columns; hydrate into the typed
        // MovementNode shape used by the matrix helper.
        const row = n as Record<string, unknown>;
        nodeById.set(row.id as string, {
          id: row.id as string,
          family: row.family as MovementFamily,
          nodeKey: row.node_key as string,
          displayName: row.display_name as string,
          prerequisites: (row.prerequisites as string[]) ?? [],
          externalLoadCapable: Boolean(row.external_load_capable),
          isometricCapable: Boolean(row.isometric_capable),
          unilateral: Boolean(row.unilateral),
          defaultTempoSeconds: row.default_tempo_seconds as number,
          tutPerRepSeconds: row.tut_per_rep_seconds as number,
          difficultyAnchor: row.difficulty_anchor as number,
          createdAt: row.created_at as unknown as Date,
        });
      }

      // Resolve a real `movements` row per node so the focus view's
      // per-movement grouping keeps working. We look up by slug ==
      // node_key against the global catalog; nodes without a matching
      // catalog movement borrow whichever movement row the day already
      // resolved to (set later, inside the day loop).
      const bwNodeSlugs = Array.from(
        new Set(Array.from(nodeById.values()).map((n) => n.nodeKey)),
      );
      const { data: bwMovements } = await supabase
        .from("movements")
        .select("id, slug, display_name")
        .in("slug", bwNodeSlugs)
        .is("user_id", null);
      const bwMovementBySlug = new Map(
        (bwMovements ?? []).map((m) => [m.slug as string, m] as const),
      );

      // Phase 4 — fetch DAG children of every current node so we can
      // stamp the "Next:" preview onto each BW prescription item.
      // One round-trip via `overlaps` against the prerequisites
      // array; results filtered to same-family children below.
      const { data: childRowsRaw } = await supabase
        .from("movement_nodes")
        .select(
          "id, family, node_key, display_name, prerequisites, external_load_capable, isometric_capable, unilateral, default_tempo_seconds, tut_per_rep_seconds, difficulty_anchor, created_at",
        )
        .overlaps("prerequisites", nodeIds);
      const childrenByCurrentId = new Map<string, MovementNode[]>();
      for (const r of (childRowsRaw ?? []) as Array<Record<string, unknown>>) {
        const childNode: MovementNode = {
          id: r.id as string,
          family: r.family as MovementFamily,
          nodeKey: r.node_key as string,
          displayName: r.display_name as string,
          prerequisites: (r.prerequisites as string[]) ?? [],
          externalLoadCapable: Boolean(r.external_load_capable),
          isometricCapable: Boolean(r.isometric_capable),
          unilateral: Boolean(r.unilateral),
          defaultTempoSeconds: r.default_tempo_seconds as number,
          tutPerRepSeconds: r.tut_per_rep_seconds as number,
          difficultyAnchor: r.difficulty_anchor as number,
          createdAt: r.created_at as unknown as Date,
        };
        for (const prereq of childNode.prerequisites) {
          if (!nodeIds.includes(prereq)) continue;
          const arr = childrenByCurrentId.get(prereq) ?? [];
          arr.push(childNode);
          childrenByCurrentId.set(prereq, arr);
        }
      }

      for (const row of bwRows ?? []) {
        const node = nodeById.get(row.current_node_id as string);
        if (!node) continue;
        const family = row.family as MovementFamily;
        const movementRow = bwMovementBySlug.get(node.nodeKey);
        const cleanRepHistory = Array.isArray(row.clean_rep_history)
          ? (row.clean_rep_history as ReadonlyArray<{ reps?: number; seconds?: number }>)
          : [];
        bwByFamily.set(family, {
          family,
          node,
          // Fallback: when the catalog has no row matching the node_key
          // we still need a uuid for movementId — borrow the node's own
          // id, which is rejected by `movement-grouping` only if it
          // collides with a real movements row (it doesn't — disjoint
          // tables). The focus view reads displayName off the item, not
          // the movements row, so the rendered name stays correct.
          movementId: movementRow?.id ?? node.id,
          movementSlug: (movementRow?.slug as string | undefined) ?? node.nodeKey,
          movementName:
            (movementRow?.display_name as string | undefined) ?? node.displayName,
          cleanRepHistory,
          candidateNextNodes: childrenByCurrentId.get(node.id) ?? [],
        });
      }
    }
  }
  const bwHasAnyFamily = bwByFamily.size > 0;

  const userTier = declaredExperienceToTier(experience);
  const resolved = new Map<string, { movementId: string; slug: string; displayName: string }>();
  // ADR 0004 — parallel map keyed by daySlotKey for dual-main-lift secondaries.
  const resolvedSecondary = new Map<string, { movementId: string; slug: string; displayName: string }>();
  const missingRoles: string[] = [];

  for (const day of activeDays) {
    if (day.kind !== "strength") continue;
    let chosen = pickStrengthMovementForBand({
      candidateSlugs: day.candidateSlugs,
      movementBySlug,
      tmMovementIds: new Set(tmByMovementId.keys()),
      tier: userTier,
    });
    // Out-of-band fallback: if the user has TMs but ONLY for movements
    // outside their declared band, honour the TM rather than blocking
    // them from training. They explicitly entered it.
    if (!chosen) {
      for (const slug of day.candidateSlugs) {
        const mv = movementBySlug.get(slug);
        if (mv && tmByMovementId.has(mv.id)) {
          if (process.env.NODE_ENV !== "production") {
            console.warn(
              `[planner] using out-of-band TM ${slug} for tier ${userTier ?? "null"} (band ${mv.experience_min}..${mv.experience_max})`,
            );
          }
          chosen = { movementId: mv.id, slug: mv.slug, displayName: mv.display_name };
          break;
        }
      }
    }
    // Fallback for the no-TM path: use the first available candidate
    // movement purely as a catalog reference. The day will be built
    // accessory-only below (no %TM items), so this is only used so the
    // row has a valid movement_id to attach the prescription to.
    if (!chosen && !hasAnyTm) {
      // Honour the tier here too — first in-band candidate, fall back
      // to first candidate of any tier.
      for (const slug of day.candidateSlugs) {
        const mv = movementBySlug.get(slug);
        if (
          mv &&
          tierInBand(userTier, mv.experience_min ?? 0, mv.experience_max ?? 4)
        ) {
          chosen = { movementId: mv.id, slug: mv.slug, displayName: mv.display_name };
          break;
        }
      }
      if (!chosen) {
        for (const slug of day.candidateSlugs) {
          const mv = movementBySlug.get(slug);
          if (mv) {
            chosen = { movementId: mv.id, slug: mv.slug, displayName: mv.display_name };
            break;
          }
        }
      }
    }
    if (chosen) resolved.set(daySlotKey(day), chosen);
    else missingRoles.push(STRENGTH_ROLE_LABELS[day.role]);

    // ADR 0004 — dual-main-lift secondary resolution. Secondary slot
    // is required (not opt-in): if the day declares a secondaryRole,
    // a TM-backed secondary movement MUST resolve or the user gets
    // the same actionable error as a missing primary TM. Otherwise
    // the user silently loses the entire upper-body maintenance dose
    // that is the whole point of ADR 0004.
    if (day.secondaryCandidateSlugs && day.secondaryCandidateSlugs.length > 0) {
      const secondary = pickSecondaryStrengthMovement({
        candidateSlugs: day.secondaryCandidateSlugs,
        movementBySlug,
        tmMovementIds: new Set(tmByMovementId.keys()),
        tier: userTier,
      });
      if (secondary) {
        resolvedSecondary.set(daySlotKey(day), secondary);
      } else if (day.secondaryRole) {
        missingRoles.push(STRENGTH_ROLE_LABELS[day.secondaryRole]);
      }
    }
  }

  if (missingRoles.length > 0 && hasAnyTm) {
    return {
      ok: false,
      error: `No TM set for: ${missingRoles.join(", ")}. Go to Settings → Training maxes and add one for each.`,
    };
  }

  // Read profile-level limitations once for the whole block — picker
  // honours `blockedRegions` + `tendinopathyActive` on every day.
  const limitationsContext = await readLimitationsContext(supabase, user.id);

  // Migration 0079 — elbow/forearm ATL ratio for the forearm
  // tendon-gate. Computed once per block-generation so we don't
  // re-query for every session. Fails open to 1.0 (no spike) when
  // history is missing.
  const userTimezoneForBlock = await getUserTimezone(user.id);
  const elbowForearmAtlRatio = parsed.data.focusMuscles.includes("forearms")
    ? await getElbowForearmAtlRatio(supabase, user.id, userTimezoneForBlock)
    : 1.0;

  // ADR 0012 — previous-block accessory recency, grouped by day-role, for
  // value-weighted block rotation. Read BEFORE the archive below so the
  // "most recent block" is the one we're about to archive. Only loaded
  // when the archetype actually runs the dynamic picker; empty otherwise
  // (and for a user's first-ever block) → byte-identical to pre-ADR-0012.
  const recencyByRole = archetype.accessoryProfile
    ? await getPreviousBlockAccessoryIdsByRole(supabase, user.id)
    : new Map<string, Set<string>>();
  const EMPTY_RECENCY: Set<string> = new Set();

  const archNow = new Date().toISOString();
  const { error: archErr } = await supabase
    .from("training_blocks")
    .update({ status: "archived", archived_at: archNow, ended_at: archNow })
    .eq("user_id", user.id)
    .eq("status", "active");
  if (archErr) return { ok: false, error: `Couldn't archive prior block: ${archErr.message}` };

  const { data: block, error: blockErr } = await supabase
    .from("training_blocks")
    .insert({
      user_id: user.id,
      archetype: archetype.id,
      started_on: parsed.data.startedOn,
      weeks: archetype.weeks,
      status: "active",
      days_per_week: parsed.data.daysPerWeek,
      day_index_overrides: dayIndexOverrides,
      power_emphasis: parsed.data.powerEmphasis,
      focus_muscles: parsed.data.focusMuscles,
      cardio_source: parsed.data.cardioSource,
      cardio_source_name: parsed.data.cardioSourceName,
      notes: hasAnyTm
        ? null
        : bwHasAnyFamily
          ? "Bodyweight block — main lifts prescribed from your assessed skill nodes."
          : "Bodyweight-only block — main-lift progression coming soon. Accessories programmed per RPE/RIR.",
    })
    .select("id")
    .single();

  if (blockErr || !block) {
    return { ok: false, error: blockErr?.message ?? "Failed to create block" };
  }

  const rows: PlannedSessionInsertRow[] = [];
  for (let week = 0; week < archetype.weeks; week++) {
    const weekProfile = archetype.weekProfiles.find((w) => w.weekIndex === week);
    const weekDeloadScale = weekProfile?.strengthVolumeScale ?? 1.0;
    const weekContext: WeekContextItem[] = [];
    for (const day of activeDays) {
      let movement: { id: string; slug: string; displayName: string };
      let finisherMovement: { id: string; slug: string; displayName: string } | undefined;
      let secondaryMovement: { id: string; slug: string; displayName: string } | undefined;

      if (day.kind === "strength") {
        const resolvedMv = resolved.get(daySlotKey(day));
        if (!resolvedMv) continue;
        movement = { id: resolvedMv.movementId, slug: resolvedMv.slug, displayName: resolvedMv.displayName };
        // ADR 0004 — dual-main-lift secondary movement, when resolved.
        const resolvedSec = resolvedSecondary.get(daySlotKey(day));
        if (resolvedSec) {
          secondaryMovement = {
            id: resolvedSec.movementId,
            slug: resolvedSec.slug,
            displayName: resolvedSec.displayName,
          };
        }
      } else if (day.kind === "cardio") {
        // PR W2 — surface D. When the cardio day declares per-tier
        // alternates, resolve to the user-tier-appropriate slug before
        // looking the movement up in the catalog. Falls back to the
        // default slug for tiers absent from the map.
        const cardioSlug = resolveCardioSlugForTier(day, userTier);
        const mv = movementBySlug.get(cardioSlug);
        if (!mv) continue;
        movement = { id: mv.id, slug: mv.slug, displayName: mv.display_name };
        if (day.finisher) {
          const fin = movementBySlug.get(day.finisher.movementSlug);
          if (fin) finisherMovement = { id: fin.id, slug: fin.slug, displayName: fin.display_name };
        }
      } else {
        // tendon
        const mv = movementBySlug.get(day.movementSlug);
        if (!mv) continue;
        movement = { id: mv.id, slug: mv.slug, displayName: mv.display_name };
      }

      const items =
        day.kind === "cardio" && parsed.data.cardioSource === "external"
          ? buildExternalCardioItems(parsed.data.cardioSourceName)
          : assemblePrescriptionItems(
              archetype,
              week,
              day,
              movement,
              finisherMovement,
              movementBySlug,
              pickerCatalog,
              weekContext,
              weekDeloadScale,
              parsed.data.powerEmphasis,
              warmupScheme,
              equipment,
              // Omit the barbell strength path when the user has no loadable
              // kit. This makes equipment the source of truth — TMs persist
              // across blocks, but the BW preset gives a bodyweight-only block
              // even if barbell TMs are saved from a previous block.
              bwActive || !hasAnyTm,
              experience,
              limitationsContext,
              secondaryMovement,
              parsed.data.focusMuscles,
              elbowForearmAtlRatio,
              day.role ? (recencyByRole.get(day.role) ?? EMPTY_RECENCY) : EMPTY_RECENCY,
            );

      // ─── Bodyweight Phase 3 — prepend BW main + back_off items ───
      // Only on strength days, only when the user has bw_progress rows
      // populated AND has no loadable kit. The matrix runs against the
      // user's current node per family; the rotation seeds off (block,
      // day, slot) so consecutive sessions don't double-stack the same
      // patterns. Pad weekIndex into the matrix's expected 0..3 domain
      // for blocks longer than 4 weeks.
      if (day.kind === "strength" && bwActive && bwHasAnyFamily) {
        const wIdx = (Math.max(0, Math.min(3, week)) as 0 | 1 | 2 | 3);
        const seed = `${block.id}:${day.dayIndex}:${day.slot ?? "single"}`;
        const userBodyweightKg = profile?.bodyweight_kg != null
          ? Number(profile.bodyweight_kg)
          : undefined;
        const bwItems = buildBwMainItemsForSession({
          byFamily: bwByFamily,
          archetype: archetype.id,
          weekIndex: wIdx,
          seed,
          equipment,
          userBodyweightKg: Number.isFinite(userBodyweightKg as number)
            ? (userBodyweightKg as number)
            : undefined,
        });
        // Prepend so BW mains come before accessories (mirrors the
        // legacy main → accessory ordering on the barbell path).
        items.unshift(...bwItems);
      }

      // ─── Phase 5 — modality classifier ───
      // Stamped on every planned session (including legacy / non-BW
      // blocks). The ceiling engine consumes `effective_stress_load`
      // when aggregating; the UI renders a small chip off
      // `session_modality`.
      const classification = classifyPlannedSession(items, archetype.id);

      // ─── Phase 5 — hinge compensation ───
      // BW-only sessions where the family rotation didn't land on
      // `hinge` AND the user has acknowledged the gap (assessment
      // completed) get a slow-tempo / eccentric / isometric hinge
      // movement appended near the end of the session.
      //
      // Gates (in order):
      //   - equipment.preset === "bodyweight_only"
      //   - day.kind === "strength" (don't inject on cardio / tendon)
      //   - profile.bw_assessment_completed_at IS NOT NULL
      //   - the BW main-lift block didn't already cover hinge
      //   - maybeInjectHingeCompensation says inject (recovery-day +
      //     no-progress-state branches short-circuit inside)
      //
      // The injected item is bucket=accessory and carries a
      // `meta.hinge_compensation` flag so settings / audit consumers
      // can find it without re-deriving from the node key.
      const bwOnly = equipment.preset === "bodyweight_only";
      const assessmentCompleted = Boolean(profile?.bw_assessment_completed_at);
      if (
        bwOnly &&
        day.kind === "strength" &&
        assessmentCompleted
      ) {
        const hingeAlreadyCovered = items.some(
          (it) => it.bw?.family === "hinge",
        );
        if (!hingeAlreadyCovered) {
          const hingeCtx = bwByFamily.get("hinge");
          const hingeProgress: BwProgress | null = hingeCtx
            ? ({
                userId: user.id,
                family: "hinge",
                currentNodeId: hingeCtx.node.id,
                accumulatedTutSeconds: 0,
                weeksAtNode: 0,
                cleanRepHistory: [],
                targetExternalLoadKg: null,
                updatedAt: new Date(),
              } as BwProgress)
            : null;
          const decision = maybeInjectHingeCompensation({
            bwProgress: hingeProgress,
            currentNode: hingeCtx?.node ?? null,
            plannedSession: {
              hasHingeMovement: false,
              sessionModality: classification.modality,
              weekIndex: (Math.max(0, Math.min(3, week)) as 0 | 1 | 2 | 3),
            },
          });
          if (decision.inject && decision.movement && hingeCtx) {
            items.push(
              buildHingeCompensationItem({
                movementId: hingeCtx.movementId,
                nodeKey: decision.movement.nodeKey,
                prescription: decision.movement,
                displayName: hingeCtx.node.displayName,
              }),
            );
          }
        }
      }
      const prescription: Prescription = { items };
      const isDeload = weekProfile?.intensityLabel === "Deload";

      let title = day.title;
      if (day.kind === "strength") {
        // When the BW path is the source of truth for this session,
        // derive the title from the first BW main movement so the day
        // card header reads "Wall handstand hold" / "Push-up" — not the
        // barbell day-template label that no longer applies. Falls
        // through to the barbell title only when the barbell path
        // actually generated items.
        const firstBwMain = bwActive
          ? items.find((it) => it.kind === "main")
          : undefined;
        if (firstBwMain) {
          const name = firstBwMain.movementName ?? movement.displayName;
          title = `${name}${isDeload ? " (deload)" : ""}`;
        } else if (hasAnyTm && !bwActive) {
          title = `${movement.displayName}${isDeload ? " (deload)" : ""}`;
        } else if (isDeload) {
          title = `${day.title} (deload)`;
        }
      } else if (isDeload) {
        title = `${day.title} (deload)`;
      }

      rows.push({
        block_id: block.id,
        user_id: user.id,
        week_index: week,
        day_index: day.dayIndex,
        slot: sanitiseSlotForMode(day.slot, allowsTwoADays),
        title,
        role: day.role,
        prescription,
        session_modality: classification.modality,
        effective_stress_load: classification.load,
      });
    }
  }

  const { error: psErr } = await supabase.from("planned_sessions").insert(rows);
  if (psErr) {
    // Roll back the block we just created so we don't leave a zombie.
    await supabase.from("training_blocks").delete().eq("id", block.id);
    return { ok: false, error: `Couldn't create planned sessions: ${psErr.message}` };
  }

  revalidatePath("/app");
  revalidatePath("/app/plan");
  revalidatePath("/app/stats");
  // Bodyweight Phase 6 — capture a diagnostics snapshot now that the
  // block's planned sessions exist (drift detection reads the
  // planner items via `planned_sessions`, so the post-creation
  // shape is the one we want frozen). Non-blocking.
  try {
    const { captureBwDiagnosticsSnapshot } = await import(
      "@/lib/planner/bw-diagnostics-snapshot"
    );
    await captureBwDiagnosticsSnapshot({ supabase, userId: user.id });
  } catch (e) {
    console.error("captureBwDiagnosticsSnapshot (createBlock) failed:", e);
  }
  return { ok: true };
}

// ─── Custom block ──────────────────────────────────────────────────

const customDayKindEnum = z.enum([
  "rest",
  "strength_squat",
  "strength_horizontal_press",
  "strength_deadlift",
  "strength_vertical_press",
  "cardio_z2_short",
  "cardio_z2_long",
  "cardio_z2_long_plus_alactic",
  "cardio_vo2",
  "cardio_alactic",
  "tendon_hsr_knee",
  "tendon_hsr_hinge",
]);

const customInputSchema = z.object({
  name: z.string().trim().max(80).optional(),
  weeks: z.coerce.number().int().min(2).max(8),
  startedOn: z.string().date(),
  waveTemplate: z.enum(["fives", "threes", "peaking_wave", "hypertrophy", "maintenance", "rebuild_flat"]),
  days: z
    .array(
      z.object({
        dayIndex: z.coerce.number().int().min(0).max(6),
        slot: z.enum(["am", "pm", "single"]).optional(),
        kind: customDayKindEnum,
        durationMinOverride: z.coerce.number().int().min(5).max(240).optional(),
      }),
    )
    .min(1)
    .max(14),
  /** Migration 0079 — per-block focus muscle groups (0–2). */
  focusMuscles: focusMusclesSchema,
});

/**
 * Create a block from a user-built custom archetype.
 *
 * Compiles the input into the same Archetype shape curated presets use,
 * then runs the standard buildPrescription pipeline. Stores
 * archetype = "custom" and the user-supplied name in the notes column.
 */
export async function createCustomBlock(formData: FormData): Promise<CreateBlockResult> {
  // The builder posts a JSON-encoded config in the "config" field.
  const configRaw = formData.get("config");
  if (typeof configRaw !== "string") return { ok: false, error: "Missing config payload" };

  let configJson: unknown;
  try {
    configJson = JSON.parse(configRaw);
  } catch (e) {
    return { ok: false, error: `Invalid config JSON: ${e instanceof Error ? e.message : String(e)}` };
  }

  const parsed = customInputSchema.safeParse(configJson);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "Invalid custom block config" };
  }

  // Defer to the compiler to convert the input into an Archetype.
  const { compileCustomArchetype, customInputMinDays } = await import("./custom");
  const daysPerWeek = customInputMinDays({ ...parsed.data, daysPerWeek: 0 });
  const archetype = compileCustomArchetype({ ...parsed.data, daysPerWeek });

  // ADR 0005 — fold missing main-lift patterns onto existing strength
  // days when the compiled custom archetype lands below the 4-strength-
  // day frequency. Pure post-compile transformation; downstream
  // resolution + row emission consume the folded shape identically to
  // the curated ENDURANCE_ANCHOR templates.
  archetype.days = foldDualMainLifts(archetype, archetype.days);

  if (daysPerWeek < 1) {
    return { ok: false, error: "Pick at least one non-rest day." };
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await getAuthUser();
  if (!user) redirect("/login");

  // Pull the user's warmup-ladder config + equipment so custom blocks
  // also pick up auto-warmups for main lifts and respect the
  // equipment-aware accessory filter. NULL → defaults via resolvers.
  const { data: customProfile } = await supabase
    .from("profiles")
    .select("warmup_scheme, equipment, barbell_kg, trap_bar_kg, plate_inventory_kg, bw_assessment_completed_at, training_experience")
    .eq("id", user.id)
    .maybeSingle();
  const customWarmupScheme = resolveWarmupScheme(customProfile?.warmup_scheme);
  const customEquipment = resolveEquipment(customProfile);
  const customExperience = resolveDeclaredExperience(customProfile?.training_experience);

  // Resolve all required movements.
  const candidateSlugs = allCandidateLiftSlugs(archetype);
  const fixedSlugs = requiredFixedSlugs(archetype);
  const accessorySlugs = allAccessorySlugs();
  const allSlugs = Array.from(new Set([...candidateSlugs, ...fixedSlugs, ...accessorySlugs]));

  const { data: movements, error: mvErr } = await supabase
    .from("movements")
    .select("id, slug, display_name, experience_min, experience_max")
    .in("slug", allSlugs)
    .is("user_id", null);
  if (mvErr) return { ok: false, error: `Movement lookup failed: ${mvErr.message}` };

  const movementBySlug = new Map((movements ?? []).map((m) => [m.slug, m]));

  const missingFixed = fixedSlugs.filter((s) => !movementBySlug.has(s));
  if (missingFixed.length > 0) {
    return {
      ok: false,
      error: `Catalog is missing required movements: ${missingFixed.join(", ")}.`,
    };
  }

  // Resolve strength roles → user variants via TM.
  const candidateMovementIds = candidateSlugs
    .map((s) => movementBySlug.get(s)?.id)
    .filter((id): id is string => !!id);
  const { data: tms, error: tmErr } = await supabase
    .from("training_maxes")
    .select("movement_id")
    .in("movement_id", candidateMovementIds);
  if (tmErr) return { ok: false, error: `TM lookup failed: ${tmErr.message}` };
  const tmMovementIds = new Set((tms ?? []).map((r) => r.movement_id));

  const customTier = declaredExperienceToTier(customExperience);
  const resolved = new Map<string, { movementId: string; slug: string; displayName: string }>();
  const resolvedSecondary = new Map<string, { movementId: string; slug: string; displayName: string }>();
  const missingRoles: string[] = [];
  for (const day of archetype.days) {
    if (day.kind !== "strength") continue;
    const chosen = pickStrengthMovementForBand({
      candidateSlugs: day.candidateSlugs,
      movementBySlug,
      tmMovementIds,
      tier: customTier,
    });
    if (chosen) resolved.set(daySlotKey(day), chosen);
    else missingRoles.push(STRENGTH_ROLE_LABELS[day.role]);

    // ADR 0004 — dual-main-lift secondary resolution (custom block path).
    // See createBlock for rationale: secondary is required, not opt-in.
    if (day.secondaryCandidateSlugs && day.secondaryCandidateSlugs.length > 0) {
      const secondary = pickSecondaryStrengthMovement({
        candidateSlugs: day.secondaryCandidateSlugs,
        movementBySlug,
        tmMovementIds,
        tier: customTier,
      });
      if (secondary) {
        resolvedSecondary.set(daySlotKey(day), secondary);
      } else if (day.secondaryRole) {
        missingRoles.push(STRENGTH_ROLE_LABELS[day.secondaryRole]);
      }
    }
  }
  if (missingRoles.length > 0) {
    return {
      ok: false,
      error: `No TM set for: ${missingRoles.join(", ")}. Go to Settings → Training maxes and add one for each.`,
    };
  }

  // Read profile-level limitations once for the whole custom block.
  const customLimitationsContext = await readLimitationsContext(
    supabase,
    user.id,
  );

  // Migration 0079 — elbow/forearm ATL ratio for the forearm gate.
  const customTzForBlock = await getUserTimezone(user.id);
  const customElbowForearmAtlRatio = parsed.data.focusMuscles.includes("forearms")
    ? await getElbowForearmAtlRatio(supabase, user.id, customTzForBlock)
    : 1.0;

  const customArchNow = new Date().toISOString();
  await supabase
    .from("training_blocks")
    .update({ status: "archived", archived_at: customArchNow, ended_at: customArchNow })
    .eq("user_id", user.id)
    .eq("status", "active");

  const { data: block, error: blockErr } = await supabase
    .from("training_blocks")
    .insert({
      user_id: user.id,
      archetype: "custom",
      started_on: parsed.data.startedOn,
      weeks: archetype.weeks,
      status: "active",
      days_per_week: daysPerWeek,
      notes: archetype.name,
      focus_muscles: parsed.data.focusMuscles,
    })
    .select("id")
    .single();
  if (blockErr || !block) return { ok: false, error: blockErr?.message ?? "Failed to create block" };

  const rows: PlannedSessionInsertRow[] = [];
  for (let week = 0; week < archetype.weeks; week++) {
    for (const day of archetype.days) {
      let movement: { id: string; slug: string; displayName: string };
      let finisherMovement: { id: string; slug: string; displayName: string } | undefined;
      let secondaryMovement: { id: string; slug: string; displayName: string } | undefined;

      if (day.kind === "strength") {
        const resolvedMv = resolved.get(daySlotKey(day));
        if (!resolvedMv) continue;
        movement = { id: resolvedMv.movementId, slug: resolvedMv.slug, displayName: resolvedMv.displayName };
        // ADR 0004 — dual-main-lift secondary movement, when resolved.
        const resolvedSec = resolvedSecondary.get(daySlotKey(day));
        if (resolvedSec) {
          secondaryMovement = {
            id: resolvedSec.movementId,
            slug: resolvedSec.slug,
            displayName: resolvedSec.displayName,
          };
        }
      } else if (day.kind === "cardio") {
        // PR W2 — surface D. Per-tier cardio resolution (custom block path).
        const cardioSlug = resolveCardioSlugForTier(day, customTier);
        const mv = movementBySlug.get(cardioSlug);
        if (!mv) continue;
        movement = { id: mv.id, slug: mv.slug, displayName: mv.display_name };
        if (day.finisher) {
          const fin = movementBySlug.get(day.finisher.movementSlug);
          if (fin) finisherMovement = { id: fin.id, slug: fin.slug, displayName: fin.display_name };
        }
      } else {
        const mv = movementBySlug.get(day.movementSlug);
        if (!mv) continue;
        movement = { id: mv.id, slug: mv.slug, displayName: mv.display_name };
      }

      const items = assemblePrescriptionItems(
        archetype,
        week,
        day,
        movement,
        finisherMovement,
        movementBySlug,
        undefined,
        undefined,
        1.0,
        false,
        customWarmupScheme,
        customEquipment,
        false,
        customExperience,
        customLimitationsContext,
        secondaryMovement,
        parsed.data.focusMuscles,
        customElbowForearmAtlRatio,
      );

      // Phase 5 — stamp modality + effective_stress_load on every
      // planned-session row so the ceiling engine and UI chip can
      // read them without re-classifying.
      const customClass = classifyPlannedSession(items, archetype.id);

      const prescription: Prescription = { items };
      const isDeload = archetype.weekProfiles.find((w) => w.weekIndex === week)?.intensityLabel === "Deload";

      let title = day.title;
      if (day.kind === "strength") {
        title = `${movement.displayName}${isDeload ? " (deload)" : ""}`;
      } else if (isDeload) {
        title = `${day.title} (deload)`;
      }

      rows.push({
        block_id: block.id,
        user_id: user.id,
        week_index: week,
        day_index: day.dayIndex,
        slot: day.slot ?? "single",
        title,
        role: day.role,
        prescription,
        session_modality: customClass.modality,
        effective_stress_load: customClass.load,
      });
    }
  }

  const { error: psErr } = await supabase.from("planned_sessions").insert(rows);
  if (psErr) {
    await supabase.from("training_blocks").delete().eq("id", block.id);
    return { ok: false, error: `Couldn't create planned sessions: ${psErr.message}` };
  }

  revalidatePath("/app");
  revalidatePath("/app/plan");
  // Bodyweight Phase 6 — diagnostics snapshot, see createBlock note.
  try {
    const { captureBwDiagnosticsSnapshot } = await import(
      "@/lib/planner/bw-diagnostics-snapshot"
    );
    await captureBwDiagnosticsSnapshot({ supabase, userId: user.id });
  } catch (e) {
    console.error("captureBwDiagnosticsSnapshot (createCustomBlock) failed:", e);
  }
  return { ok: true };
}

const blockIdSchema = z.object({ id: z.string().uuid() });

// ─── updateBlockFocus (migration 0079) ────────────────────────────
// Per-block "focus muscle groups" edit affordance on /app/plan. RLS-
// scoped: the user_id eq filter combined with Supabase RLS guarantees
// the caller can only mutate their own block. Idempotent: writing the
// same focus list twice is a no-op (the column update is value-equal).
//
// Block-mid changes apply to FUTURE sessions only. Currently the
// planner materialises every session eagerly at createBlock time, so
// already-generated planned_sessions keep their pre-edit prescription.
// Re-materialising remaining sessions would invalidate user notes /
// drawer state on planned rows the user has already inspected, so the
// pragmatic choice is: new focus → next block, or "Start a new block"
// to apply mid-stream. Documented behaviour.

const updateBlockFocusSchema = z.object({
  id: z.string().uuid(),
  focusMuscles: focusMusclesSchema,
});

export type UpdateBlockFocusResult =
  | { ok: true; focusMuscles: string[] }
  | { ok: false; error: string };

export async function updateBlockFocus(
  formData: FormData,
): Promise<UpdateBlockFocusResult> {
  const parsed = updateBlockFocusSchema.safeParse({
    id: formData.get("id"),
    focusMuscles: formData
      .getAll("focusMuscles")
      .map((v) => (typeof v === "string" ? v : ""))
      .filter((v) => v.length > 0),
  });
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "Invalid input" };
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await getAuthUser();
  if (!user) return { ok: false, error: "Not signed in" };

  // RLS-scoped update — eq user_id is belt-and-braces alongside the
  // RLS policy. We do NOT filter on status so the user can also
  // pre-set focus on a queued (rare today) or just-archived block in
  // a follow-up flow.
  const { error } = await supabase
    .from("training_blocks")
    .update({ focus_muscles: parsed.data.focusMuscles })
    .eq("id", parsed.data.id)
    .eq("user_id", user.id);
  if (error) return { ok: false, error: error.message };

  revalidatePath("/app/plan");
  revalidatePath("/app");
  return { ok: true, focusMuscles: parsed.data.focusMuscles };
}

const endBlockSchema = z.object({
  id: z.string().uuid(),
  reason: z.string().max(280).optional(),
});

export async function endBlock(formData: FormData): Promise<void> {
  const parsed = endBlockSchema.safeParse({
    id: formData.get("id"),
    reason: (formData.get("reason") as string | null) ?? undefined,
  });
  if (!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? "Invalid input");
  const supabase = await createClient();
  const nowIso = new Date().toISOString();

  // Capture engine context BEFORE the archive write so the snapshot
  // reflects the block as the user last saw it (active, week N of K).
  // DC-K4: every override carries the engine state at decision time.
  const [{ data: blockRow }, { data: completionRow }] = await Promise.all([
    supabase
      .from("training_blocks")
      .select("archetype, weeks, started_on")
      .eq("id", parsed.data.id)
      .maybeSingle(),
    supabase
      .from("planned_sessions")
      .select("id, completed_session_id, skipped_at", { count: "exact" })
      .eq("block_id", parsed.data.id),
  ]);

  await supabase
    .from("training_blocks")
    .update({ status: "archived", archived_at: nowIso, ended_at: nowIso })
    .eq("id", parsed.data.id);

  const {
    data: { user },
  } = await getAuthUser();
  if (user) {
    const totalPlanned = completionRow?.length ?? 0;
    const totalDone = (completionRow ?? []).filter(
      (r) => r.completed_session_id || r.skipped_at,
    ).length;
    const percentThrough = totalPlanned > 0 ? totalDone / totalPlanned : 0;
    const weeks = blockRow?.weeks as number | undefined;
    const startedOn = blockRow?.started_on as string | undefined;
    let weeksCompleted: number | undefined;
    if (startedOn) {
      const startMs = Date.parse(`${startedOn}T00:00:00Z`);
      if (!Number.isNaN(startMs)) {
        const days = Math.max(0, Math.floor((Date.now() - startMs) / 86_400_000));
        weeksCompleted = Math.floor(days / 7);
        if (typeof weeks === "number") {
          weeksCompleted = Math.min(weeksCompleted, weeks);
        }
      }
    }
    await recordOverrideEvent(supabase, {
      userId: user.id,
      eventType: "manual_end",
      occurredAt: nowIso,
      blockId: parsed.data.id,
      reason: parsed.data.reason ?? null,
      context: {
        archetype: blockRow?.archetype as string | undefined,
        weeks,
        weeksCompleted,
        percentThrough: Number(percentThrough.toFixed(3)),
      },
    });
  }

  revalidatePath("/app");
  revalidatePath("/app/plan");
}

/**
 * Soft-delete a training block. Distinct from `endBlock` which writes
 * status='archived' to mark "no longer active". `deleteBlock` is the
 * stronger intent: remove from history, recoverable for 30 days via
 * the Trash page. AGENTS.md DC-K4 — destructive, reversible.
 *
 * Cascade is implicit: every query that lists planned_sessions joins
 * through the block and the block filter `deleted_at IS NULL` hides
 * the children too. Hard cascade to planned_sessions only fires when
 * the block is permanently deleted (FK ON DELETE CASCADE in 0008).
 *
 * RLS (training_blocks_update_self) covers ownership; the explicit
 * `eq("user_id", ...)` is defense in depth.
 */
export async function deleteBlock(
  formData: FormData,
): Promise<{ ok: true; blockId: string } | { ok: false; error: string }> {
  const parsed = blockIdSchema.safeParse({ id: formData.get("id") });
  if (!parsed.success) return { ok: false, error: parsed.error.issues[0]?.message ?? "Invalid input" };
  const supabase = await createClient();
  const {
    data: { user },
  } = await getAuthUser();
  if (!user) return { ok: false, error: "Not signed in." };

  const { error } = await supabase
    .from("training_blocks")
    .update({ deleted_at: new Date().toISOString() })
    .eq("id", parsed.data.id)
    .eq("user_id", user.id);
  if (error) return { ok: false, error: error.message };

  revalidatePath("/app");
  revalidatePath("/app/plan");
  revalidatePath("/app/plan/history");
  revalidatePath("/app/stats");
  revalidatePath("/app/settings/trash");
  return { ok: true, blockId: parsed.data.id };
}

/** Restore a soft-deleted block — flips `deleted_at` back to NULL. */
export async function restoreBlock(
  id: string,
): Promise<{ ok: true } | { ok: false; error: string }> {
  if (!id) return { ok: false, error: "Missing block id." };
  const supabase = await createClient();
  const {
    data: { user },
  } = await getAuthUser();
  if (!user) return { ok: false, error: "Not signed in." };

  const { error } = await supabase
    .from("training_blocks")
    .update({ deleted_at: null })
    .eq("id", id)
    .eq("user_id", user.id);
  if (error) return { ok: false, error: error.message };

  revalidatePath("/app");
  revalidatePath("/app/plan");
  revalidatePath("/app/plan/history");
  revalidatePath("/app/stats");
  revalidatePath("/app/settings/trash");
  return { ok: true };
}

/**
 * Hard-delete a block. Only callable from the Trash page after the
 * user types the block's archetype name as type-to-confirm. Cascades
 * to planned_sessions via the FK in migration 0008
 * (planned_sessions.block_id ON DELETE CASCADE).
 */
export async function permanentlyDeleteBlock(
  id: string,
): Promise<{ ok: true } | { ok: false; error: string }> {
  if (!id) return { ok: false, error: "Missing block id." };
  const supabase = await createClient();
  const {
    data: { user },
  } = await getAuthUser();
  if (!user) return { ok: false, error: "Not signed in." };

  const { error } = await supabase
    .from("training_blocks")
    .delete()
    .eq("id", id)
    .eq("user_id", user.id);
  if (error) return { ok: false, error: error.message };

  revalidatePath("/app");
  revalidatePath("/app/plan");
  revalidatePath("/app/plan/history");
  revalidatePath("/app/stats");
  revalidatePath("/app/settings/trash");
  return { ok: true };
}

const linkPlannedSchema = z.object({
  plannedId: z.string().uuid(),
  sessionId: z.string().uuid(),
});

/**
 * Link a past planned_session to an already-logged sessions row. Used
 * by the past-unfulfilled match modal in the calendar views: when the
 * user identifies a Strava-imported activity (or any logged session
 * on the same calendar day) as the realisation of a planned slot, we
 * point `completed_session_id` at it. RLS + the inner-join through
 * training_blocks ensures only the owning user can mutate the row.
 */
export async function linkPlannedToSession(formData: FormData): Promise<void> {
  const parsed = linkPlannedSchema.safeParse({
    plannedId: formData.get("plannedId"),
    sessionId: formData.get("sessionId"),
  });
  if (!parsed.success) return;
  const supabase = await createClient();
  await supabase
    .from("planned_sessions")
    .update({ completed_session_id: parsed.data.sessionId })
    .eq("id", parsed.data.plannedId);
  revalidatePath("/app");
  revalidatePath("/app/plan");
}

const skipSchema = z.object({
  id: z.string().uuid(),
  reason: z.string().max(280).optional(),
});

export async function skipPlannedSession(formData: FormData): Promise<void> {
  const parsed = skipSchema.safeParse({
    id: formData.get("id"),
    reason: (formData.get("reason") as string | null) ?? undefined,
  });
  if (!parsed.success) return;
  const supabase = await createClient();
  const skippedAt = new Date().toISOString();

  // Read planned + block context BEFORE the update so the audit row
  // carries the engine state the user actually saw when skipping.
  const { data: planned } = await supabase
    .from("planned_sessions")
    .select(
      "id, user_id, block_id, week_index, day_index, training_blocks!inner(archetype, started_on)",
    )
    .eq("id", parsed.data.id)
    .maybeSingle();

  await supabase
    .from("planned_sessions")
    .update({ skipped_at: skippedAt })
    .eq("id", parsed.data.id);

  if (planned) {
    const block = (planned as unknown as {
      training_blocks: { archetype: string; started_on: string };
    }).training_blocks;
    const startedOn = block?.started_on as string | undefined;
    const weekIndex = planned.week_index as number;
    const dayIndex = planned.day_index as number;
    let weekday: number | undefined;
    if (startedOn) {
      const startMs = Date.parse(`${startedOn}T12:00:00Z`);
      if (!Number.isNaN(startMs)) {
        const dayMs = startMs + (weekIndex * 7 + dayIndex) * 86_400_000;
        const d = new Date(dayMs);
        weekday = ((d.getUTCDay() + 6) % 7) + 1;
      }
    }
    await recordOverrideEvent(supabase, {
      userId: planned.user_id as string,
      eventType: "skip",
      occurredAt: skippedAt,
      plannedSessionId: parsed.data.id,
      blockId: planned.block_id as string,
      reason: parsed.data.reason ?? null,
      context: {
        archetype: block?.archetype,
        weekIndex,
        dayIndex,
        weekday,
      },
    });
  }

  revalidatePath("/app");
  revalidatePath("/app/plan");
}

const unskipSchema = z.object({ id: z.string().uuid() });

const moveSchema = z.object({
  id: z.string().uuid(),
  weekIndex: z.number().int().min(0),
  dayIndex: z.number().int().min(0).max(6),
});

/**
 * Move a planned session to a new (week_index, day_index) slot. If the
 * target slot already holds a planned_sessions row (and neither row is
 * completed), the two rows swap. Out-of-block target weeks are rejected
 * silently. Completed/skipped sessions can be moved but the partner
 * (if any) is left in place.
 *
 * UI-only operation: the engine's stress budget / recovery math is
 * unchanged — the user can already reorder days via the wizard.
 */
export async function movePlannedSession(formData: FormData): Promise<void> {
  const parsed = moveSchema.safeParse({
    id: formData.get("id"),
    weekIndex: Number(formData.get("weekIndex")),
    dayIndex: Number(formData.get("dayIndex")),
  });
  if (!parsed.success) return;
  const supabase = await createClient();
  const {
    data: { user },
  } = await getAuthUser();
  if (!user) redirect("/login");

  const { data: planned } = await supabase
    .from("planned_sessions")
    .select("id, block_id, week_index, day_index, slot")
    .eq("id", parsed.data.id)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!planned) return;

  const { data: block } = await supabase
    .from("training_blocks")
    .select("weeks")
    .eq("id", planned.block_id)
    .maybeSingle();
  if (!block) return;
  if (parsed.data.weekIndex >= (block.weeks as number)) return;

  // No-op if already on the target slot.
  if (
    planned.week_index === parsed.data.weekIndex &&
    planned.day_index === parsed.data.dayIndex
  ) {
    return;
  }

  // Find what (if anything) currently sits on the target slot. Limit to
  // the same block + same slot label so a 2-a-day doesn't get clobbered
  // by a 1-a-day swap (we only swap matching slots).
  const { data: existing } = await supabase
    .from("planned_sessions")
    .select("id, week_index, day_index, slot")
    .eq("block_id", planned.block_id)
    .eq("user_id", user.id)
    .eq("week_index", parsed.data.weekIndex)
    .eq("day_index", parsed.data.dayIndex);

  const target = (existing ?? []).find((r) => r.slot === planned.slot);

  if (target && target.id !== planned.id) {
    // Atomic-ish swap with rollback on partial failure. See
    // ./swap.ts for the parking-slot strategy + rationale. The helper
    // throws on any DB error so we surface failures to the caller
    // instead of silently leaving a row stranded at the guard slot.
    await swapPlannedSessions({
      client: supabase as unknown as Parameters<typeof swapPlannedSessions>[0]["client"],
      userId: user.id,
      sourceId: planned.id,
      sourceWeek: planned.week_index,
      sourceDay: planned.day_index,
      targetId: target.id,
      targetWeek: parsed.data.weekIndex,
      targetDay: parsed.data.dayIndex,
      blockWeeks: block.weeks as number,
    });
  } else {
    const { error: moveErr } = await supabase
      .from("planned_sessions")
      .update({ week_index: parsed.data.weekIndex, day_index: parsed.data.dayIndex })
      .eq("id", planned.id)
      .eq("user_id", user.id);
    if (moveErr) {
      throw new Error(
        `movePlannedSession: failed to move ${planned.id}: ${moveErr.message}`,
      );
    }
  }

  // Moving a day clears any explicit planned_at (the absolute timestamp
  // referred to the OLD calendar date — keeping it would put the
  // session on the wrong wall-clock day).
  const { error: clearErr } = await supabase
    .from("planned_sessions")
    .update({ planned_at: null })
    .in("id", target ? [planned.id, target.id] : [planned.id])
    .eq("user_id", user.id);
  if (clearErr) {
    throw new Error(
      `movePlannedSession: failed to clear planned_at after move: ${clearErr.message}`,
    );
  }

  revalidatePath("/app");
  revalidatePath("/app/plan");
}

export async function unskipPlannedSession(formData: FormData): Promise<void> {
  const parsed = unskipSchema.safeParse({ id: formData.get("id") });
  if (!parsed.success) return;
  const supabase = await createClient();
  await supabase
    .from("planned_sessions")
    .update({ skipped_at: null })
    .eq("id", parsed.data.id);
  revalidatePath("/app");
  revalidatePath("/app/plan");
}

const setPlannedTimeSchema = z.object({
  id: z.string().uuid(),
  hhmm: z.string().regex(/^\d{2}:\d{2}$/, "Use HH:mm"),
});

/**
 * Set an explicit planned_at on a planned_session. Computes the UTC instant
 * from the user's profile timezone + the day's calendar date + the HH:mm
 * the user entered. Empty / cleared input is treated as null (revert to
 * profile window default).
 */
export async function setPlannedTime(formData: FormData): Promise<void> {
  const raw = {
    id: formData.get("id"),
    hhmm: formData.get("hhmm"),
  };
  // Empty time field clears the override.
  const supabase = await createClient();
  const {
    data: { user },
  } = await getAuthUser();
  if (!user) redirect("/login");

  const idValid = typeof raw.id === "string" && /^[0-9a-f-]{36}$/i.test(raw.id);
  if (!idValid) return;
  const id = raw.id as string;

  if (!raw.hhmm || raw.hhmm === "") {
    await supabase
      .from("planned_sessions")
      .update({ planned_at: null })
      .eq("id", id)
      .eq("user_id", user.id);
    revalidatePath("/app");
    revalidatePath("/app/plan");
    return;
  }

  const parsed = setPlannedTimeSchema.safeParse(raw);
  if (!parsed.success) return;

  // Look up the planned session + its block to compute the day's date.
  const { data: planned } = await supabase
    .from("planned_sessions")
    .select("id, week_index, day_index, block_id")
    .eq("id", parsed.data.id)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!planned) return;

  const { data: block } = await supabase
    .from("training_blocks")
    .select("started_on")
    .eq("id", planned.block_id)
    .maybeSingle();
  if (!block) return;

  const { data: profile } = await supabase
    .from("profiles")
    .select("timezone")
    .eq("id", user.id)
    .maybeSingle();
  const tz = profile?.timezone ?? "UTC";

  // Compute the calendar date this slot falls on.
  const { dayDate } = await import("./queries");
  const date = dayDate(block.started_on, planned.week_index, planned.day_index);
  const { localTimeToUTC } = await import("./time-of-day");
  const utc = localTimeToUTC(date, parsed.data.hhmm, tz);

  await supabase
    .from("planned_sessions")
    .update({ planned_at: utc.toISOString() })
    .eq("id", parsed.data.id)
    .eq("user_id", user.id);

  revalidatePath("/app");
  revalidatePath("/app/plan");
}

const startPlannedSchema = z.object({ id: z.string().uuid() });

/**
 * Maximum allowed back-date for retroactive session logging, in days.
 *
 * Anything beyond two weeks is almost certainly user error (a typo
 * in the date picker, or "I'll just back-fill the whole previous
 * month"), which would silently scramble adherence + ESL attribution.
 * The picker pre-fill defaults to the planned date so the legitimate
 * "I logged yesterday's workout today" path never bumps against this.
 */
const MAX_RETRO_PERFORMED_AT_DAYS = 14;

const YMD_RE = /^\d{4}-\d{2}-\d{2}$/;

/**
 * Validate a retroactive `performedAt` YYYY-MM-DD against the user
 * timezone. Returns the start-of-day UTC instant for the picked date,
 * or throws a user-facing Error.
 */
async function resolveRetroPerformedAt(
  performedAt: string,
  userId: string,
): Promise<Date> {
  // Cheap structural check first — we don't want to round-trip to
  // profiles just to reject "lol nope".
  if (!YMD_RE.test(performedAt)) {
    throw new Error("Invalid performed_at: expected YYYY-MM-DD");
  }
  const [y, m, d] = performedAt.split("-").map((s) => Number.parseInt(s, 10));
  const probe = new Date(Date.UTC(y, m - 1, d));
  if (
    Number.isNaN(probe.getTime()) ||
    probe.getUTCFullYear() !== y ||
    probe.getUTCMonth() !== m - 1 ||
    probe.getUTCDate() !== d
  ) {
    throw new Error("Invalid performed_at: not a real calendar date");
  }
  const tz = await getUserTimezone(userId);
  const today = todayYmd(tz);
  const delta = daysBetweenYmd(performedAt, today); // today - picked
  if (delta < 0) {
    throw new Error("performed_at cannot be in the future");
  }
  if (delta > MAX_RETRO_PERFORMED_AT_DAYS) {
    throw new Error(
      `performed_at cannot be more than ${MAX_RETRO_PERFORMED_AT_DAYS} days in the past`,
    );
  }
  return ymdToUtc(performedAt, tz);
}

/**
 * Start a real session from a planned slot.
 *
 * Creates a sessions row pre-populated with the planned title + a set_log
 * stub per prescription item (no weights yet — user logs them as actual sets),
 * and links it back to the planned_session.
 *
 * Honours an optional `performedAt` form field (YYYY-MM-DD) — when
 * present, the new session is back-dated to start-of-day in the user's
 * timezone. See `startSessionDirect` for the validation rules.
 */
export async function startSessionFromPlan(formData: FormData): Promise<void> {
  const parsed = startPlannedSchema.safeParse({ id: formData.get("id") });
  if (!parsed.success) throw new Error("Invalid planned session id");
  const rawPerformedAt = formData.get("performedAt");
  const performedAt =
    typeof rawPerformedAt === "string" && rawPerformedAt.length > 0
      ? rawPerformedAt
      : undefined;
  await startSessionDirect(parsed.data.id, performedAt ? { performedAt } : undefined);
}

/**
 * Start a planned session WITHOUT a pre-session check-in.
 *
 * This is the single source of truth for materialising a planned
 * session into a real `sessions` row. The legacy
 * `startCheckInSession` path that also wrote `fatigue` / `soreness`
 * onto the new sessions row was removed when the pre-workout
 * interstitial was deleted, and the follow-up Today-page wellness
 * check-in card has since also been retired (see
 * chore/retire-wellness-checkin). The `wellness` table and engine
 * read path stay intact for optionality. Callers that need the
 * URL-driven version use the `/app/sessions/start/[plannedId]` page
 * which auto-invokes this helper and redirects.
 *
 * Side effects (must stay in lockstep with the planner's expectations):
 *   1. INSERT a new `sessions` row carrying the planned title, slot,
 *      and planned_at (so the planner can correlate it back).
 *   2. UPDATE the matching `planned_sessions` row's
 *      `completed_session_id` so the plan calendar knows the row is
 *      now linked-and-in-progress.
 *   3. Revalidate `/app` + `/app/plan` so the CTAs flip on the next
 *      paint.
 *   4. Redirect to `/app/sessions/<new-id>` — the session log surface.
 *
 * Idempotent re-entry: if the planned row already has a
 * `completed_session_id`, we skip the insert and redirect to that
 * session (matches the behaviour the deleted interstitial had).
 */
export async function startSessionDirect(
  plannedId: string,
  options?: { performedAt?: string },
): Promise<never> {
  const parsed = startPlannedSchema.safeParse({ id: plannedId });
  if (!parsed.success) throw new Error("Invalid planned session id");

  const supabase = await createClient();
  const {
    data: { user },
  } = await getAuthUser();
  if (!user) redirect("/login");

  // Resolve the back-date BEFORE the planned-session lookup so we
  // surface the error path before any DB mutation. `resolveRetro…`
  // throws a user-facing message that the form action surfaces via
  // Next's error overlay.
  const retroPerformedAt =
    options?.performedAt != null
      ? await resolveRetroPerformedAt(options.performedAt, user.id)
      : null;

  const { data: planned } = await supabase
    .from("planned_sessions")
    .select("id, title, slot, planned_at, prescription, completed_session_id, user_id")
    .eq("id", parsed.data.id)
    .maybeSingle();

  if (!planned) throw new Error("Planned session not found");
  if (planned.user_id !== user.id) throw new Error("Planned session not found");

  // Idempotent re-entry: reuse the existing linked session if any.
  if (planned.completed_session_id) {
    redirect(`/app/sessions/${planned.completed_session_id}`);
  }

  const sessionPayload: {
    user_id: string;
    title: string;
    slot: string;
    planned_at: string | null;
    performed_at?: string;
  } = {
    user_id: user.id,
    title: planned.title,
    slot: planned.slot ?? "single",
    planned_at: planned.planned_at,
  };
  if (retroPerformedAt) {
    sessionPayload.performed_at = retroPerformedAt.toISOString();
  }

  const { data: session, error: sessErr } = await supabase
    .from("sessions")
    .insert(sessionPayload)
    .select("id")
    .single();

  if (sessErr || !session) throw new Error(sessErr?.message ?? "Failed to start session");

  // Conditional link so a concurrent caller (e.g. middle-click that
  // bypasses the client-side one-tap lock) cannot overwrite an earlier
  // winner. If the UPDATE affects zero rows, another request already
  // linked first — delete our orphan insert and redirect to the winner.
  const { data: linked, error: linkErr } = await supabase
    .from("planned_sessions")
    .update({ completed_session_id: session.id })
    .eq("id", planned.id)
    .is("completed_session_id", null)
    .select("id, completed_session_id")
    .maybeSingle();

  if (linkErr) throw new Error(linkErr.message);

  if (!linked) {
    // Lost the race. Clean up the orphaned session and reuse the winner.
    await supabase.from("sessions").delete().eq("id", session.id);
    const { data: winner } = await supabase
      .from("planned_sessions")
      .select("completed_session_id")
      .eq("id", planned.id)
      .maybeSingle();
    if (winner?.completed_session_id) {
      revalidatePath("/app");
      revalidatePath("/app/plan");
      redirect(`/app/sessions/${winner.completed_session_id}`);
    }
    throw new Error("Failed to link planned session after race");
  }

  revalidatePath("/app");
  revalidatePath("/app/plan");
  redirect(`/app/sessions/${session.id}`);
}
