import type {
  Prescription,
  PrescriptionItem,
  MovementFamily,
  BwProgress,
} from "@hta/db";
import type { DeclaredExperience } from "@hta/engine";
import {
  type Archetype,
  type ArchetypeId,
  type CardioDay,
  type DayTemplate,
  daySlotKey,
  deloadCardioPlan,
  cardioProgressionPlan,
  resolveCardioSlugForTier,
} from "./archetypes";
import { assemblePrescriptionItems } from "./assemble-prescription";
import { expandPrescriptionSetItems } from "./expand-prescription-sets";
import { sanitiseSlotForMode } from "./slot";
import {
  type CatalogMovement,
  type WeekAccessoryHistoryItem,
} from "./accessory-picker";
import { type LimitationsContext } from "./limitations-context";
import { type CardioCatalogMovement } from "./cardio-catalog";
import {
  type PreferredCardioModality,
  blockUsesRunningCardio,
  resolvePreferredCardioModality,
} from "./preferred-cardio-modality";
import {
  modalityPreferenceForDay,
  type GoalModality,
} from "./cardio-modality-plan";
import {
  computeInterferenceVolumeBonus,
  scalarModalityKey,
} from "./interference-volume";
import type { Equipment } from "@/lib/settings/equipment-schema";
import {
  buildBwMainItemsForSession,
  type BwFamilyContext,
} from "./bw-main-items";
import {
  classifySessionModality,
  effectiveStressLoad,
  type ClassifierMovement,
  type SessionModality,
} from "./session-modality";
import {
  maybeInjectHingeCompensation,
  HINGE_COMPENSATION_FAMILY,
} from "./hinge-compensation";
import { type FocusMuscle } from "./focus-muscles";
import { type EffortPreference } from "./effort-preference";
import { type SecondaryFocus } from "./secondary-focus";
import { type AccessoryVolumeLevel } from "./accessory-volume";
import { type WarmupScheme } from "./warmups";
import { descriptiveSessionTitle } from "./session-title";
import { buildExternalCardioItems } from "./external-cardio";

/**
 * Wire shape for `planned_sessions` INSERTs via the Supabase REST API.
 *
 * PostgREST takes the literal JS keys you send and looks them up as
 * column names — it does NOT translate from Drizzle's camelCase property
 * names to the underlying snake_case DB columns. The Drizzle-derived
 * `NewPlannedSession` type uses camelCase (blockId, userId, weekIndex,
 * …) which PostgREST rejects with PGRST204 ("Could not find the
 * 'blockId' column of 'planned_sessions' in the schema cache").
 *
 * This type is intentionally typed against the *DB column names* so the
 * TypeScript compiler will reject any future drift back to camelCase.
 */
export type PlannedSessionInsertRow = {
  block_id: string;
  user_id: string;
  week_index: number;
  day_index: number;
  slot: "single" | "am" | "pm";
  title: string;
  role: string;
  prescription: Prescription;
  /**
   * Phase 5 — modality classifier output. NULL on rows generated by
   * code paths that opted out of the classifier (none today, but the
   * column is nullable in the DB so legacy callers stay valid).
   */
  session_modality?: SessionModality | null;
  /**
   * Phase 5 — hard-set count × modality multiplier. NULL when the
   * session has no hard sets (rest day, etc.) or when the modality
   * could not be computed.
   */
  effective_stress_load?: number | null;
};

/** Resolved main / secondary movement reference attached to a strength day. */
type MovementResolution = { movementId: string; slug: string; displayName: string };

/**
 * Map a curated CardioDay's `cardioKind` to the classifier's mode tag.
 * The classifier only distinguishes Z2 / HIIT / mixed; finer-grained
 * shapes (alactic vs threshold vs VO2) collapse into HIIT or mixed
 * because they hit the same recovery-cost branch.
 */
function cardioModeFor(
  kind: PrescriptionItem["kind"],
): "z2" | "hiit" | "mixed" {
  if (kind === "cardio_z2") return "z2";
  if (kind === "cardio_alactic" || kind === "cardio_vo2") return "hiit";
  if (kind === "cardio_threshold") return "mixed";
  return "mixed";
}

/**
 * Convert the planned-session prescription `items` array (the same
 * shape that gets serialised onto `planned_sessions.prescription`)
 * into the classifier's input contract.
 *
 * Strength items map by `kind`:
 *   - main → bucket=main
 *   - back_off → bucket=back_off
 *   - accessory / tendon / power_potentiation → bucket=accessory
 *   - warmup → kind=warmup (the classifier ignores these)
 *
 * Cardio items emit a single `cardioBlock` carrying `durationMinutes`.
 * `estimatedHardSets` for cardio is set to 0 — the multiplier covers
 * the recovery cost, the hard-set count is for strength work.
 */
function itemsToClassifierMovements(
  items: ReadonlyArray<PrescriptionItem>,
  archetype: ArchetypeId,
): ClassifierMovement[] {
  const out: ClassifierMovement[] = [];
  for (const it of items) {
    if (it.kind === "warmup") {
      out.push({ kind: "warmup", archetype, estimatedHardSets: 0 });
      continue;
    }
    if (
      it.kind === "cardio_z2" ||
      it.kind === "cardio_alactic" ||
      it.kind === "cardio_vo2" ||
      it.kind === "cardio_threshold" ||
      it.kind === "cardio_external"
    ) {
      out.push({
        kind: "conditioning",
        archetype,
        cardioBlock: {
          // External cardio collapses to z2 for stress-budget purposes:
          // the user is following an outside program so we can't know
          // the actual intensity. Z2 is the safest default — the
          // multiplier under-counts hard runs (acceptable) instead of
          // over-counting easy ones (would suppress strength volume).
          mode: it.kind === "cardio_external" ? "z2" : cardioModeFor(it.kind),
          // Phase 1 — external blocks carry no `durationMin`. 0 lets the
          // calendar / modality classifier still register a cardio day
          // without inflating effective_stress_load against unknown work.
          durationMinutes: it.durationMin ?? 0,
        },
        estimatedHardSets: 0,
      });
      continue;
    }
    const sets = Math.max(0, it.sets ?? 1);
    if (it.kind === "main") {
      out.push({
        kind: "main",
        archetype,
        bucket: "main",
        estimatedHardSets: sets,
        bw: it.bw
          ? {
              prescriptionType: it.bw.prescriptionType,
              family: (it.bw.family as MovementFamily | undefined) ?? "push_h",
              nodeDifficulty: 0,
            }
          : undefined,
      });
      continue;
    }
    if (it.kind === "back_off") {
      out.push({
        kind: "back_off",
        archetype,
        bucket: "back_off",
        estimatedHardSets: sets,
      });
      continue;
    }
    // accessory / tendon / power_potentiation
    out.push({
      kind: "accessory",
      archetype,
      bucket: "accessory",
      estimatedHardSets: sets,
    });
  }
  return out;
}

/**
 * Stamp the modality + effective-stress-load on a planned session.
 * Centralised so createBlock and createCustomBlock produce the same
 * shape — they're the only two callers that build planner rows.
 */
export function classifyPlannedSession(
  items: ReadonlyArray<PrescriptionItem>,
  archetype: ArchetypeId,
): { modality: SessionModality; load: number } {
  const movs = itemsToClassifierMovements(items, archetype);
  const modality = classifySessionModality({ movements: movs });
  const hardSets = movs.reduce(
    (acc, m) => acc + (m.kind === "warmup" ? 0 : Math.max(0, m.estimatedHardSets)),
    0,
  );
  const load = effectiveStressLoad({ modality, hardSets });
  return { modality, load };
}

/**
 * Build the prescription-item shape for an injected hinge-compensation
 * movement. The injected item is bucketed as `accessory` so existing
 * focus-view / logging paths render it without special-casing; the
 * `meta.hinge_compensation` flag distinguishes it from a normal
 * accessory pick for downstream consumers (settings page, audit).
 */
function buildHingeCompensationItem(args: {
  movementId: string;
  nodeKey: string;
  prescription: {
    nodeKey: string;
    prescriptionType: "isometric_hold" | "tempo_reps" | "reps";
    sets: number;
    reps?: number;
    holdSeconds?: number;
    tempoEccentricSec: number;
    targetRir: number;
    intensityCue: string;
  };
  displayName: string;
}): PrescriptionItem {
  const p = args.prescription;
  const item: PrescriptionItem = {
    movementId: args.movementId,
    movementSlug: p.nodeKey,
    movementName: args.displayName,
    kind: "accessory",
    sets: p.sets,
    targetRir: { min: p.targetRir, max: p.targetRir },
    tempoEccentricSec: p.tempoEccentricSec,
    intensityCue: p.intensityCue,
    intensityLabel: "hinge compensation",
    notes:
      "Posterior-chain compensation — your session didn't include a hinge pattern.",
    bw: {
      prescriptionType: p.prescriptionType,
      sets: p.sets,
      reps: p.reps,
      holdSeconds: p.holdSeconds,
      tempoEccentricSec: p.tempoEccentricSec,
      targetRir: p.targetRir,
      restSeconds: 90,
      intensityCue: p.intensityCue,
      nodeKey: p.nodeKey,
      nodeDisplayName: args.displayName,
      family: HINGE_COMPENSATION_FAMILY,
    },
    meta: { hinge_compensation: true, hinge_compensation_node: p.nodeKey },
  };
  if (p.prescriptionType === "isometric_hold" && p.holdSeconds != null) {
    item.holdSec = { min: p.holdSeconds, max: p.holdSeconds };
  } else if (p.reps != null) {
    item.reps = p.reps;
  }
  return item;
}

/**
 * Every input the block-level derivations and the per-session week×day
 * assembly loop read. Captured once by `createBlock` after its DB-loading
 * phase, then handed to {@link assembleBlockSessions}. The row-identity
 * fields (`block_id` / `user_id`) are NOT part of this context — they are
 * passed as explicit `blockId` / `userId` parameters so the assembler stays
 * a pure function of training inputs.
 */
export interface BlockAssemblyContext {
  // ─── Structure ───────────────────────────────────────────────────
  /** The resolved archetype (weeks, weekProfiles, id, day templates). */
  archetype: Archetype;
  /** Active day templates after frequency folding + wizard placements. */
  activeDays: DayTemplate[];
  /** Two-a-day preference — controls slot sanitisation on every row. */
  allowsTwoADays: boolean;

  // ─── Per-day strength-movement resolution ────────────────────────
  /** Primary main lift per strength day, keyed by `daySlotKey(day)`. */
  resolved: Map<string, MovementResolution>;
  /** ADR 0004 dual-main-lift secondary, keyed by `daySlotKey(day)`. */
  resolvedSecondary: Map<string, MovementResolution>;
  /** Global movement catalog (id / slug / display_name) keyed by slug. */
  movementBySlug: Map<string, { id: string; slug: string; display_name: string }>;
  /** Full picker catalog with role tags (empty for legacy archetypes). */
  pickerCatalog: CatalogMovement[];

  // ─── User profile-derived locals ─────────────────────────────────
  /** Declared-experience tier (0..4) or `null` when undeclared. */
  userTier: number | null;
  /** Resolved warmup-ladder configuration. */
  warmupScheme: WarmupScheme;
  /** Resolved equipment inventory. */
  equipment: Equipment;
  /** Declared training experience or `null`. */
  experience: DeclaredExperience | null;
  /** Profile-level limitations (blocked regions / tendinopathy). */
  limitationsContext: LimitationsContext;
  /** Elbow/forearm ATL ratio for the forearm tendon-gate (1.0 = no spike). */
  elbowForearmAtlRatio: number;
  /** ADR 0012 previous-block accessory ids by day-role. */
  recencyByRole: Map<string, Set<string>>;
  /** ADR 0016 effort dial. */
  effortPreference: EffortPreference;
  /** ADR 0020 resolved wizard secondary focus. */
  secondaryFocus: SecondaryFocus;
  /** ADR 0024 per-block accessory volume level. */
  accessoryVolume: AccessoryVolumeLevel;
  /** Raw `profiles.bodyweight_kg` (used for BW main-lift scaling). */
  profileBodyweightKg: number | string | null | undefined;
  /** Raw `profiles.bw_assessment_completed_at` (gates hinge compensation). */
  bwAssessmentCompletedAt: string | null | undefined;

  // ─── Cardio context ──────────────────────────────────────────────
  /** ADR 0017 ranked cardio-modality preference. */
  preferredCardioModalities: PreferredCardioModality[];
  /** ADR 0039 resolved block GOAL cardio modality. */
  goalModality: GoalModality;
  /** Cardio catalog (empty unless a preference / event goal is present). */
  cardioCatalog: CardioCatalogMovement[];
  /** Cardio catalog indexed by slug. */
  cardioCatalogBySlug: Map<string, CardioCatalogMovement>;

  // ─── Bodyweight context ──────────────────────────────────────────
  /** True when the user has no loadable kit (BW main-lift path). */
  bwActive: boolean;
  /** True when at least one training-max is logged. */
  hasAnyTm: boolean;
  /** Per-family BW main-lift context from `bw_progress` + `movement_nodes`. */
  bwByFamily: Map<MovementFamily, BwFamilyContext>;
  /** True when `bwByFamily` has at least one family populated. */
  bwHasAnyFamily: boolean;

  // ─── Wizard inputs (parsed.data) ─────────────────────────────────
  /** Phase 1 external-cardio toggle (`internal` | `external`). */
  cardioSource: "internal" | "external";
  /** Free-text external-program label, or null. */
  cardioSourceName: string | null;
  /** Wizard "Add power emphasis" toggle. */
  powerEmphasis: boolean;
  /** Migration 0079 per-block focus muscle groups. */
  focusMuscles: readonly FocusMuscle[];
}

/**
 * Pure, behaviour-preserving extraction of `createBlock`'s per-session
 * prescription assembly. Computes the block-level derivations (running
 * cardio, pressing main-lift count, interference bonus) and runs the
 * week×day loop, returning the `planned_sessions` insert rows.
 *
 * This function performs NO DB access — every input arrives via `ctx`.
 * `blockId` / `userId` are the only row-identity fields and are kept out
 * of `ctx` so the assembler is a pure function of the training inputs.
 */
export function assembleBlockSessions(
  ctx: BlockAssemblyContext,
  blockId: string,
  userId: string,
): PlannedSessionInsertRow[] {
  const {
    archetype,
    activeDays,
    allowsTwoADays,
    resolved,
    resolvedSecondary,
    movementBySlug,
    pickerCatalog,
    userTier,
    warmupScheme,
    equipment,
    experience,
    limitationsContext,
    elbowForearmAtlRatio,
    recencyByRole,
    effortPreference,
    secondaryFocus,
    accessoryVolume,
    profileBodyweightKg,
    bwAssessmentCompletedAt,
    preferredCardioModalities,
    goalModality,
    cardioCatalog,
    cardioCatalogBySlug,
    bwActive,
    hasAnyTm,
    bwByFamily,
    bwHasAnyFamily,
    cardioSource,
    cardioSourceName,
    powerEmphasis,
    focusMuscles,
  } = ctx;
  const EMPTY_RECENCY: Set<string> = new Set();

  const rows: PlannedSessionInsertRow[] = [];
  // ADR 0034 — does this block run? Resolve the cardio modality of each cardio
  // day once (running unless the user substituted it away) so the durability
  // floor can prioritise Achilles/calf HSR for runners.
  //
  // External cardio (`cardio_source = 'external'`, e.g. a Runna plan) carries no
  // in-app modality signal, but it is overwhelmingly running — so treat an
  // external-cardio block as running-impact by default. The cost of a wrong
  // guess is a single calf/Achilles HSR slot; the cost of missing it for a real
  // runner is the #1 overuse-injury gap.
  const runningCardio =
    cardioSource === "external"
      ? true
      : blockUsesRunningCardio(
          activeDays
            .filter((d): d is CardioDay => d.kind === "cardio")
            .map((d) => ({
              cardioKind:
                d.cardioKind === "cardio_external" ? "cardio_other" : d.cardioKind,
              defaultSlug: resolveCardioSlugForTier(d, userTier),
            })),
          {
            preferred: preferredCardioModalities,
            ownedCardio: equipment.cardio,
            userTier,
            catalog: cardioCatalog,
          },
        );
  // ADR 0035/0037 — count the block's weekly pressing main-lift exposures
  // (vertical_press + horizontal_press, primary AND secondary, across every
  // strength day). Drives the cuff floor (count > 0) and scales the pull
  // requirement so push:pull stays balanced however many pressing patterns the
  // structure programs. Scales with days/week, archetype, and dual-main folding.
  const pressingMainLiftCount = activeDays.reduce((n, d) => {
    if (d.kind !== "strength") return n;
    const isPress = (r: string | undefined) =>
      r === "vertical_press" || r === "horizontal_press";
    return n + (isPress(d.role) ? 1 : 0) + (isPress(d.secondaryRole) ? 1 : 0);
  }, 0);
  // ADR 0039 — the block's cardio days, for per-day specificity classification.
  const cardioDays = activeDays.filter(
    (d): d is CardioDay => d.kind === "cardio",
  );
  // ADR 0040 — interference-aware accessory headroom. When the cardio catalog is
  // loaded (an event goal or a preference is present, so diversification is
  // possible), compare each cardio day's PLANNED modality (post-ADR-0039) to the
  // archetype's DEFAULT modality and grant a small (≤ +1) accessory-item bonus
  // when the planned mix interferes less with strength. With no catalog there is
  // no diversification → planned == default → 0 → byte-identical.
  let interferenceItemBonus = 0;
  if (cardioCatalog.length > 0) {
    const defaultMix: Record<string, number> = {};
    const plannedMix: Record<string, number> = {};
    for (const day of cardioDays) {
      const minutes = day.durationMin ?? 0;
      if (minutes <= 0) continue;
      const defaultSlug = resolveCardioSlugForTier(day, userTier);
      const defModality = cardioCatalogBySlug.get(defaultSlug)?.modality ?? null;
      const defKey = scalarModalityKey(defModality);
      defaultMix[defKey] = (defaultMix[defKey] ?? 0) + minutes;
      const dayPreferred = modalityPreferenceForDay({
        day,
        allCardioDays: cardioDays,
        archetypeId: archetype.id,
        secondaryFocus,
        goal: goalModality,
        userPreferred: preferredCardioModalities,
      });
      const resolved = resolvePreferredCardioModality({
        defaultSlug,
        cardioKind:
          day.cardioKind === "cardio_external" ? "cardio_other" : day.cardioKind,
        preferred: dayPreferred,
        ownedCardio: equipment.cardio,
        userTier,
        catalog: cardioCatalog,
      });
      const planModality =
        cardioCatalogBySlug.get(resolved.slug)?.modality ?? defModality;
      const planKey = scalarModalityKey(planModality);
      plannedMix[planKey] = (plannedMix[planKey] ?? 0) + minutes;
    }
    interferenceItemBonus = computeInterferenceVolumeBonus({
      defaultMinutesByModality: defaultMix,
      plannedMinutesByModality: plannedMix,
      archetypeId: archetype.id,
    });
  }
  for (let week = 0; week < archetype.weeks; week++) {
    const weekProfile = archetype.weekProfiles.find((w) => w.weekIndex === week);
    const weekDeloadScale = weekProfile?.strengthVolumeScale ?? 1.0;
    const weekAccessoryHistory: WeekAccessoryHistoryItem[] = [];
    for (const day of activeDays) {
      let movement: { id: string; slug: string; displayName: string };
      let finisherMovement: { id: string; slug: string; displayName: string } | undefined;
      let secondaryMovement: { id: string; slug: string; displayName: string } | undefined;
      // ADR 0037 — on the deload week a maximal VO2 day is rendered as a
      // downgraded effort; holds the effective cardio day for the assembler.
      let cardioDayOverride: CardioDay | undefined;

      if (day.kind === "strength") {
        const resolvedMv = resolved.get(daySlotKey(day));
        if (!resolvedMv) continue;
        movement = { id: resolvedMv.movementId, slug: resolvedMv.slug, displayName: resolvedMv.displayName };
        // ADR 0004 — dual-main-lift secondary movement, when resolved.
        const resolvedSec = resolvedSecondary.get(daySlotKey(day));
        if (resolvedSec) {
          secondaryMovement = {
            id: resolvedSec.movementId,
            slug: resolvedSec.slug,
            displayName: resolvedSec.displayName,
          };
        }
      } else if (day.kind === "cardio") {
        // PR W2 — surface D. When the cardio day declares per-tier
        // alternates, resolve to the user-tier-appropriate slug before
        // looking the movement up in the catalog. Falls back to the
        // default slug for tiers absent from the map.
        //
        // ADR 0037 — coherent deload: on the deload week downgrade the maximal
        // VO2 session to a sub-maximal touch (easy Z2, or one threshold session
        // at high frequency) and drop the alactic finisher, so the recovery week
        // reduces intensity and not merely volume.
        const dPlan = deloadCardioPlan(day, weekProfile, activeDays.length, userTier);
        const effCardioKind = dPlan?.cardioKindOverride ?? day.cardioKind;
        const baseCardioSlug =
          dPlan?.slugOverride ?? resolveCardioSlugForTier(day, userTier);
        // ADR 0017 + 0039 — substitute toward the per-day modality preference.
        // ADR 0039 decides the ranking (goal-specific work → goal modality;
        // diversifiable base → lower-interference modality on strength blocks),
        // and reuses the ADR 0017 resolver for equipment/tier/kind feasibility.
        // Returns the user's preference list unchanged when there is no event
        // goal, so non-event blocks are byte-identical.
        const dayPreferred = modalityPreferenceForDay({
          day,
          allCardioDays: cardioDays,
          archetypeId: archetype.id,
          secondaryFocus,
          goal: goalModality,
          userPreferred: preferredCardioModalities,
        });
        const resolvedCardio = resolvePreferredCardioModality({
          defaultSlug: baseCardioSlug,
          cardioKind:
            effCardioKind === "cardio_external" ? "cardio_other" : effCardioKind,
          preferred: dayPreferred,
          ownedCardio: equipment.cardio,
          userTier,
          catalog: cardioCatalog,
        });
        const sub = resolvedCardio.substituted
          ? cardioCatalogBySlug.get(resolvedCardio.slug)
          : undefined;
        if (sub) {
          movement = { id: sub.id, slug: sub.slug, displayName: sub.displayName };
        } else {
          const mv = movementBySlug.get(resolvedCardio.slug);
          if (!mv) continue;
          movement = { id: mv.id, slug: mv.slug, displayName: mv.display_name };
        }
        if (day.finisher && !dPlan?.dropFinisher) {
          const fin = movementBySlug.get(day.finisher.movementSlug);
          if (fin) finisherMovement = { id: fin.id, slug: fin.slug, displayName: fin.display_name };
        }
        // ADR 0038 — cardio mesocycle progression on the build weeks (mutually
        // exclusive with the deload plan, which owns the deload week). Easy-Z2
        // volume creep + VO2 peak-week density bump, scaled to cardio emphasis.
        const pPlan = dPlan
          ? null
          : cardioProgressionPlan({ day, archetype, weekIndex: week, secondaryFocus });
        if (dPlan || pPlan) {
          cardioDayOverride = {
            ...day,
            ...(dPlan
              ? {
                  cardioKind: effCardioKind,
                  finisher: dPlan.dropFinisher ? undefined : day.finisher,
                  // Clear the VO2-specific protocol / HR cap when converted.
                  ...(dPlan.cardioKindOverride
                    ? { hrCap: undefined, protocolNote: undefined }
                    : {}),
                }
              : {}),
            ...(pPlan?.durationMinOverride != null
              ? { durationMin: pPlan.durationMinOverride }
              : {}),
            ...(pPlan?.protocolNoteOverride != null
              ? { protocolNote: pPlan.protocolNoteOverride }
              : {}),
          };
        }
      } else {
        // tendon
        const mv = movementBySlug.get(day.movementSlug);
        if (!mv) continue;
        movement = { id: mv.id, slug: mv.slug, displayName: mv.display_name };
      }

      const items =
        day.kind === "cardio" && cardioSource === "external"
          ? buildExternalCardioItems(cardioSourceName)
          : assemblePrescriptionItems(
              archetype,
              week,
              cardioDayOverride ?? day,
              movement,
              finisherMovement,
              movementBySlug,
              pickerCatalog,
              weekAccessoryHistory,
              weekDeloadScale,
              powerEmphasis,
              warmupScheme,
              equipment,
              // Omit the barbell strength path when the user has no loadable
              // kit. This makes equipment the source of truth — TMs persist
              // across blocks, but the BW preset gives a bodyweight-only block
              // even if barbell TMs are saved from a previous block.
              bwActive || !hasAnyTm,
              experience,
              limitationsContext,
              secondaryMovement,
              focusMuscles,
              elbowForearmAtlRatio,
              day.role ? (recencyByRole.get(day.role) ?? EMPTY_RECENCY) : EMPTY_RECENCY,
              effortPreference,
              secondaryFocus,
              accessoryVolume,
              undefined, // aestheticTargetMask (planned-block path)
              undefined, // variationSeed (planned-block path)
              runningCardio,
              pressingMainLiftCount,
              interferenceItemBonus,
            );

      // ─── Bodyweight Phase 3 — prepend BW main + back_off items ───
      // Only on strength days, only when the user has bw_progress rows
      // populated AND has no loadable kit. The matrix runs against the
      // user's current node per family; the rotation seeds off (block,
      // day, slot) so consecutive sessions don't double-stack the same
      // patterns. Pad weekIndex into the matrix's expected 0..3 domain
      // for blocks longer than 4 weeks.
      if (day.kind === "strength" && bwActive && bwHasAnyFamily) {
        const wIdx = (Math.max(0, Math.min(3, week)) as 0 | 1 | 2 | 3);
        const seed = `${blockId}:${day.dayIndex}:${day.slot ?? "single"}`;
        const userBodyweightKg = profileBodyweightKg != null
          ? Number(profileBodyweightKg)
          : undefined;
        const bwItems = buildBwMainItemsForSession({
          byFamily: bwByFamily,
          archetype: archetype.id,
          weekIndex: wIdx,
          seed,
          equipment,
          userBodyweightKg: Number.isFinite(userBodyweightKg as number)
            ? (userBodyweightKg as number)
            : undefined,
        });
        // Prepend so BW mains come before accessories (mirrors the
        // legacy main → accessory ordering on the barbell path).
        items.unshift(...bwItems);
      }

      // ─── Phase 5 — modality classifier ───
      // Stamped on every planned session (including legacy / non-BW
      // blocks). The ceiling engine consumes `effective_stress_load`
      // when aggregating; the UI renders a small chip off
      // `session_modality`.
      const classification = classifyPlannedSession(items, archetype.id);

      // ─── Phase 5 — hinge compensation ───
      // BW-only sessions where the family rotation didn't land on
      // `hinge` AND the user has acknowledged the gap (assessment
      // completed) get a slow-tempo / eccentric / isometric hinge
      // movement appended near the end of the session.
      //
      // Gates (in order):
      //   - equipment.preset === "bodyweight_only"
      //   - day.kind === "strength" (don't inject on cardio / tendon)
      //   - profile.bw_assessment_completed_at IS NOT NULL
      //   - the BW main-lift block didn't already cover hinge
      //   - maybeInjectHingeCompensation says inject (recovery-day +
      //     no-progress-state branches short-circuit inside)
      //
      // The injected item is bucket=accessory and carries a
      // `meta.hinge_compensation` flag so settings / audit consumers
      // can find it without re-deriving from the node key.
      const bwOnly = equipment.preset === "bodyweight_only";
      const assessmentCompleted = Boolean(bwAssessmentCompletedAt);
      if (
        bwOnly &&
        day.kind === "strength" &&
        assessmentCompleted
      ) {
        const hingeAlreadyCovered = items.some(
          (it) => it.bw?.family === "hinge",
        );
        if (!hingeAlreadyCovered) {
          const hingeCtx = bwByFamily.get("hinge");
          const hingeProgress: BwProgress | null = hingeCtx
            ? ({
                userId: userId,
                family: "hinge",
                currentNodeId: hingeCtx.node.id,
                accumulatedTutSeconds: 0,
                weeksAtNode: 0,
                cleanRepHistory: [],
                targetExternalLoadKg: null,
                updatedAt: new Date(),
              } as BwProgress)
            : null;
          const decision = maybeInjectHingeCompensation({
            bwProgress: hingeProgress,
            currentNode: hingeCtx?.node ?? null,
            plannedSession: {
              hasHingeMovement: false,
              sessionModality: classification.modality,
              weekIndex: (Math.max(0, Math.min(3, week)) as 0 | 1 | 2 | 3),
            },
          });
          if (decision.inject && decision.movement && hingeCtx) {
            items.push(
              buildHingeCompensationItem({
                movementId: hingeCtx.movementId,
                nodeKey: decision.movement.nodeKey,
                prescription: decision.movement,
                displayName: hingeCtx.node.displayName,
              }),
            );
          }
        }
      }
      const prescription: Prescription = {
        items: expandPrescriptionSetItems(items),
      };
      const isDeload = weekProfile?.intensityLabel === "Deload";

      // Descriptive default name: "<Modality> · <focus>". Strength days
      // name their main lift(s); cardio/tendon days keep their type label.
      // See `descriptiveSessionTitle` — title is a display-only label.
      let base = day.title;
      if (day.kind === "strength") {
        // When the BW path is the source of truth for this session,
        // derive the title from the BW main movement(s) so the day
        // card header reads "Wall handstand hold" / "Push-up" — not the
        // barbell day-template label that no longer applies. Falls
        // through to the barbell title only when the barbell path
        // actually generated items.
        const firstBwMain = bwActive
          ? items.find((it) => it.kind === "main")
          : undefined;
        if (firstBwMain) {
          const bwMainNames = items
            .filter((it) => it.kind === "main")
            .map((it) => it.movementName)
            .filter((n): n is string => Boolean(n));
          base =
            bwMainNames.length > 0
              ? bwMainNames.join(" + ")
              : movement.displayName;
        } else if (hasAnyTm && !bwActive) {
          // Barbell strength day. A folded dual-main-lift day (ADR
          // 0004/0005) is named after BOTH resolved lifts — "Front Squat
          // + Standing Overhead Press" — so it isn't mislabelled after
          // only its first lift and the heading-dedup heuristic doesn't
          // hide just one of the two movement cards.
          base =
            day.secondaryRole && secondaryMovement
              ? `${movement.displayName} + ${secondaryMovement.displayName}`
              : movement.displayName;
        }
      }
      // ADR 0044 (UX) — an external-cardio day ("Logged via Runna") is NOT
      // touched by the engine's deload downgrade (ADR 0037), so tagging it
      // "(deload)" implies a change the app didn't make. Suppress the suffix on
      // those days; engine-controlled cardio + strength days keep it.
      const isExternalCardioDay =
        day.kind === "cardio" && cardioSource === "external";
      const title = descriptiveSessionTitle(
        day.kind,
        base,
        isDeload && !isExternalCardioDay,
      );

      rows.push({
        block_id: blockId,
        user_id: userId,
        week_index: week,
        day_index: day.dayIndex,
        slot: sanitiseSlotForMode(day.slot, allowsTwoADays),
        title,
        role: day.role,
        prescription,
        session_modality: classification.modality,
        effective_stress_load: classification.load,
      });
    }
  }

  return rows;
}
