/**
 * Strip leaked engine-bucket prefixes from legacy `notes` strings before
 * we render them to the user. New picks no longer write these prefixes;
 * this protects rows that were generated by older planner runs.
 *
 * Leaked prefixes (historical):
 *   - "Weekly tissue floor: …"  (durability bucket)
 *   - "Functional minimum: …"   (functional bucket)
 *   - "Per-muscle volume: …"    (aesthetic bucket)
 */
export function cleanPrescriptionNotes(notes: string | null | undefined): string | null {
  if (!notes) return null;
  const leakPatterns = [
    /^Weekly tissue floor:/i,
    /^Functional minimum:/i,
    /^Per-muscle volume:/i,
  ];
  if (leakPatterns.some((re) => re.test(notes))) return null;
  return notes;
}
