import sharp from "sharp";
import { writeFile, mkdir, readFile } from "node:fs/promises";

// iOS launch ("splash") screen generator.
//
// iOS shows an `apple-touch-startup-image` while a home-screen PWA cold-
// launches. Without one the user sees a blank flash; with a device-matched
// image the launch feels native. Each device needs an exact-pixel image
// plus a media query keyed on CSS pt size + devicePixelRatio + orientation.
//
// The app is portrait-locked (manifest `orientation: portrait`) so we only
// emit portrait images — landscape launches still fall back gracefully to
// the manifest background_color.
//
// Source of truth for the matrix lives here; this script also writes the
// matching TS module consumed by `layout.tsx` so the <link> tags can never
// drift from the generated PNGs.

// { w, h } are CSS points (portrait); r is devicePixelRatio.
const DEVICES = [
  { w: 320, h: 568, r: 2 }, // iPhone SE (1st gen)
  { w: 375, h: 667, r: 2 }, // iPhone 8 / SE 2-3
  { w: 414, h: 736, r: 3 }, // iPhone 8 Plus
  { w: 375, h: 812, r: 3 }, // iPhone X / XS / 11 Pro / 12-13 mini
  { w: 414, h: 896, r: 2 }, // iPhone XR / 11
  { w: 414, h: 896, r: 3 }, // iPhone XS Max / 11 Pro Max
  { w: 390, h: 844, r: 3 }, // iPhone 12 / 13 / 14
  { w: 428, h: 926, r: 3 }, // iPhone 12-13 Pro Max / 14 Plus
  { w: 393, h: 852, r: 3 }, // iPhone 14 Pro / 15 / 15 Pro / 16
  { w: 430, h: 932, r: 3 }, // iPhone 14 Pro Max / 15 Plus / 15 Pro Max / 16 Plus
  { w: 402, h: 874, r: 3 }, // iPhone 16 Pro
  { w: 440, h: 956, r: 3 }, // iPhone 16 Pro Max
  { w: 768, h: 1024, r: 2 }, // iPad mini / 9.7"
  { w: 810, h: 1080, r: 2 }, // iPad 10.2"
  { w: 820, h: 1180, r: 2 }, // iPad Air 10.9"
  { w: 834, h: 1112, r: 2 }, // iPad Pro 10.5"
  { w: 834, h: 1194, r: 2 }, // iPad Pro 11"
  { w: 1024, h: 1366, r: 2 }, // iPad Pro 12.9"
];

const BG = { r: 15, g: 19, b: 16, alpha: 1 }; // #0f1310 (manifest background_color)

const repoRoot = new URL("../", import.meta.url);
const wordmarkPath = new URL(
  "apps/web/public/branding/sxc-wordmark-dark.svg",
  repoRoot,
);
const outDir = new URL("apps/web/public/splash/", repoRoot);
const moduleOut = new URL("apps/web/src/lib/pwa/splash-screens.ts", repoRoot);

await mkdir(outDir, { recursive: true });
const wordmarkSvg = await readFile(wordmarkPath);

const entries = [];

for (const { w, h, r } of DEVICES) {
  const pxW = w * r;
  const pxH = h * r;

  // Brand wordmark sized to ~62% of the (portrait) short edge.
  const logoW = Math.round(pxW * 0.62);
  const logo = await sharp(wordmarkSvg, { density: 384 })
    .resize({ width: logoW })
    .png()
    .toBuffer();
  const logoMeta = await sharp(logo).metadata();
  const logoH = logoMeta.height ?? 0;

  const buffer = await sharp({
    create: { width: pxW, height: pxH, channels: 4, background: BG },
  })
    .composite([
      {
        input: logo,
        top: Math.round((pxH - logoH) / 2),
        left: Math.round((pxW - logoW) / 2),
      },
    ])
    .png()
    .toBuffer();

  const fileName = `apple-splash-${pxW}-${pxH}.png`;
  await writeFile(new URL(fileName, outDir), buffer);
  console.log(`wrote splash/${fileName} (${buffer.length} bytes)`);

  const media =
    `screen and (device-width: ${w}px) and (device-height: ${h}px) ` +
    `and (-webkit-device-pixel-ratio: ${r}) and (orientation: portrait)`;
  entries.push({ url: `/splash/${fileName}`, media });
}

const moduleSrc = `// AUTO-GENERATED by scripts/generate-splash.mjs — do not edit by hand.
// Run \`node scripts/generate-splash.mjs\` to regenerate after changing the
// device matrix or brand lockup.

export type AppleSplashScreen = { url: string; media: string };

export const APPLE_SPLASH_SCREENS: AppleSplashScreen[] = ${JSON.stringify(
  entries,
  null,
  2,
)};
`;

await writeFile(moduleOut, moduleSrc);
console.log(`wrote ${entries.length} splash entries to splash-screens.ts`);
