-- sync-migrations-tracking.sql
--
-- AUTO-GENERATED by scripts/sync-migrations-tracking.ts. Re-run that
-- script (with --write) after editing any migration file in
-- packages/db/drizzle/ that you also applied out-of-band.
--
-- Backfills the missing rows in `drizzle.__drizzle_migrations` for
-- migrations 0016-0029 (applied via the Supabase dashboard
-- rather than `drizzle-kit migrate`). Safe to re-run — the WHERE NOT
-- EXISTS guard makes it idempotent.
--
-- Apply via:
--   psql "$DATABASE_URL" -f packages/db/sync-migrations-tracking.sql
--   # or paste into the Supabase SQL editor

CREATE SCHEMA IF NOT EXISTS drizzle;

CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (
  id SERIAL PRIMARY KEY,
  hash text NOT NULL,
  created_at bigint
);

WITH wanted (tag, hash, created_at) AS (
  VALUES
    ('0016_strava_integration'        , 'e2bc09061358197f4efbe8f2a64688b4e9ba28997bd03227b836c6c63f038355', 1779480000000::bigint),
    ('0017_events'                    , '14dd27bc1b3d3e8be918191fa6cd23a68a28a8bbf8097d7e96bb745fed7ce96f', 1779501600000::bigint),
    ('0018_accessory_roles'           , '2b598a1ed8f32e2d8d339db47287a3a2be8a54e675e20bb8f9e74ff286483102', 1779523200000::bigint),
    ('0019_tag_accessory_roles'       , '272ddfccb0487d445efc635caff6bd0f08ddc930b05fd2c4fc20baaa0e289bc9', 1779544800000::bigint),
    ('0020_block_day_index_overrides' , '884178be3ee2bb1b4af1b09be56d8e2a86fb694cca5e02b19f6745bee2bf4edb', 1779566400000::bigint),
    ('0021_training_experience'       , 'd8c1ec0db9983814cc09d8d4071b3ea970ffd0bf3b862150cfef33428e95a0e4', 1779588000000::bigint),
    ('0022_power_emphasis'            , 'a06104f89fd1a959be36fad099fbcedc7740c7ee03c67a482d857a30403bd0ab', 1779609600000::bigint),
    ('0023_power_movement_tagging'    , '16008187561aca084a2104ab59d3933a4043781c2f5094ddc282b70992adcd7c', 1779631200000::bigint),
    ('0024_power_movements_seed'      , '811c8d84dc06f4e7fa2853e86ef7e393547b83ee883da721321516af514fafee', 1779652800000::bigint),
    ('0025_block_lifecycle_timestamps', '2ead5ab2c77864d111dce36823d899a9221138648ee87042831a8d6899dfda87', 1779674400000::bigint),
    ('0026_soft_delete'               , '84bab8e8868a7314f957edc40393c2d2c8600d5bb33541888fd795269a3f4993', 1779696000000::bigint),
    ('0027_daily_check_ins'           , '82f0de1ca9ff511f5a39591c4de719750b73430741ac05a62dad41c0a42b21ab', 1779717600000::bigint),
    ('0028_engine_override_events'    , '2329a24a30b92c5ee3822f0a3fabd9ef3bf70944429c73175e64d7f354a370d5', 1779739200000::bigint),
    ('0029_region_state_history'      , '07d5ace50d1d30d7f7595303ab4257e5c81f732ee3e63a867e6a6117d028dfd7', 1779760800000::bigint)
)
INSERT INTO drizzle.__drizzle_migrations (hash, created_at)
SELECT w.hash, w.created_at
FROM wanted w
WHERE NOT EXISTS (
  SELECT 1 FROM drizzle.__drizzle_migrations m WHERE m.hash = w.hash
);

-- Quick post-run sanity check (uncomment to use):
-- SELECT COUNT(*) AS tracked_rows FROM drizzle.__drizzle_migrations;
