/**
 * sync-migrations-tracking.ts
 *
 * Regenerates `packages/db/sync-migrations-tracking.sql` from the
 * migration files in `packages/db/drizzle/`.
 *
 * Why: drizzle stores `sha256(<file contents>)` and that hash is
 * line-ending-sensitive. The committed static SQL file uses
 * LF-normalized hashes (the canonical form on Linux/CI). If your
 * local checkout has CRLF endings, the static hashes won't match
 * what `drizzle-kit migrate` will compute against your files —
 * run this script to emit a SQL block that matches your local
 * environment exactly.
 *
 * Usage:
 *   pnpm --filter @hta/db tsx scripts/sync-migrations-tracking.ts
 *     # → writes the regenerated SQL to stdout
 *
 *   pnpm --filter @hta/db tsx scripts/sync-migrations-tracking.ts --write
 *     # → overwrites packages/db/sync-migrations-tracking.sql in place
 *
 * The script is read-only against the DB; the generated SQL is what
 * you actually run against Supabase / psql.
 */
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Migrations 0000–0015 were applied through drizzle-kit migrate from
// the start, so __drizzle_migrations already tracks them. Out-of-band
// migrations (applied via the Supabase dashboard rather than
// `drizzle-kit migrate`) need a backfill row in __drizzle_migrations
// so the next migrate run doesn't try to re-apply them.
//
// Range is INCLUSIVE on both ends. Bump LAST_UNTRACKED_IDX whenever
// another migration is again applied out-of-band; otherwise leave it
// alone (new migrations applied normally through `drizzle-kit migrate`
// must NOT appear in this list, or drizzle will skip applying them).
const FIRST_UNTRACKED_IDX = 16;
const LAST_UNTRACKED_IDX = 26;

// Anchor `created_at` ~roughly to when each migration was authored.
// Drizzle doesn't actually care about this value for migrate behavior;
// it's purely audit-trail. Spaced 6h apart from a fixed anchor so the
// ordering survives any future re-runs.
const BASE_WHEN_MS = 1779480000000;
const STEP_MS = 6 * 60 * 60 * 1000;

const here = dirname(fileURLToPath(import.meta.url));
const drizzleDir = join(here, "..", "drizzle");
const outPath = join(here, "..", "sync-migrations-tracking.sql");

type Entry = { tag: string; hash: string; createdAt: number };

function lfNormalizedHash(path: string): string {
  const raw = readFileSync(path, "utf8").replace(/\r\n/g, "\n");
  return createHash("sha256").update(raw, "utf8").digest("hex");
}

function collectEntries(): Entry[] {
  const files = readdirSync(drizzleDir)
    .filter((f) => /^\d{4}_.+\.sql$/.test(f))
    .sort();
  const out: Entry[] = [];
  for (const f of files) {
    const idx = Number.parseInt(f.slice(0, 4), 10);
    if (idx < FIRST_UNTRACKED_IDX || idx > LAST_UNTRACKED_IDX) continue;
    const tag = f.replace(/\.sql$/, "");
    const hash = lfNormalizedHash(join(drizzleDir, f));
    const createdAt = BASE_WHEN_MS + (idx - FIRST_UNTRACKED_IDX) * STEP_MS;
    out.push({ tag, hash, createdAt });
  }
  return out;
}

function renderSql(entries: Entry[]): string {
  const tagWidth = Math.max(...entries.map((e) => e.tag.length)) + 2;
  const rows = entries
    .map(
      (e, i) =>
        `    (${`'${e.tag}'`.padEnd(tagWidth)}, '${e.hash}', ${e.createdAt}::bigint)${
          i === entries.length - 1 ? "" : ","
        }`,
    )
    .join("\n");

  return `-- sync-migrations-tracking.sql
--
-- AUTO-GENERATED by scripts/sync-migrations-tracking.ts. Re-run that
-- script (with --write) after editing any migration file in
-- packages/db/drizzle/ that you also applied out-of-band.
--
-- Backfills the missing rows in \`drizzle.__drizzle_migrations\` for
-- migrations ${entries[0]?.tag.slice(0, 4)}-${entries[entries.length - 1]?.tag.slice(0, 4)} (applied via the Supabase dashboard
-- rather than \`drizzle-kit migrate\`). Safe to re-run — the WHERE NOT
-- EXISTS guard makes it idempotent.
--
-- Apply via:
--   psql "$DATABASE_URL" -f packages/db/sync-migrations-tracking.sql
--   # or paste into the Supabase SQL editor

CREATE SCHEMA IF NOT EXISTS drizzle;

CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (
  id SERIAL PRIMARY KEY,
  hash text NOT NULL,
  created_at bigint
);

WITH wanted (tag, hash, created_at) AS (
  VALUES
${rows}
)
INSERT INTO drizzle.__drizzle_migrations (hash, created_at)
SELECT w.hash, w.created_at
FROM wanted w
WHERE NOT EXISTS (
  SELECT 1 FROM drizzle.__drizzle_migrations m WHERE m.hash = w.hash
);

-- Quick post-run sanity check (uncomment to use):
-- SELECT COUNT(*) AS tracked_rows FROM drizzle.__drizzle_migrations;
`;
}

function main(): void {
  const entries = collectEntries();
  if (entries.length === 0) {
    console.error("No untracked migrations found — nothing to do.");
    process.exit(0);
  }
  const sql = renderSql(entries);
  if (process.argv.includes("--write")) {
    writeFileSync(outPath, sql, "utf8");
    console.error(`Wrote ${entries.length} entries → ${outPath}`);
  } else {
    process.stdout.write(sql);
  }
}

main();
